### ISSUE TITLE
loopback-angular should not require database connection

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback-sdk-angular#106]
I don't know why it's needed, but the generation phase needs a db connection.

Can this be made so that it doesn't? 

TIA :)

**Comment by Klowner** [comment]
Due to trying to build my project out to a Docker instance, I also ran into this issue. My hack solution was to create a datasources.build.json with all my datasource connectors set to "memory".

Far from ideal, but seems to do the trick.

**Comment by bajtos** [comment]
Hello! Back in 2016, we have implemented support for lazy connection setup, allowing the application to configure all datasources but letting the connectors to defer connecting until the first database request is made. See https://github.com/strongloop/loopback-datasource-juggler/issues/463#issuecomment-227155433 for more details.

The lazy mode can be triggered by setting the environment variable `LB_LAZYCONNECT_DATASOURCES` to a truthy value (e.g. `1`).

It would be great if the CLI tool `lb-ng` could set this environment variable automatically, before loading the app. See here: https://github.com/strongloop/loopback-sdk-angular-cli/blob/56299ceb5fa10ddde408ecbfa9140ad75166cce3/bin/lb-ng.js#L36-L37

A similar change could be made to our Grunt and Gulp plugins.

Any volunteers willing to contribute these improvements?

**Comment by bajtos** [comment]
With the release of LoopBack 4.0 GA (see the [announcement](https://strongloop.com/strongblog/loopback-4-ga)), this SDK has entered Active LTS mode which means we are no longer accepting new features (see our [LTS policy](https://loopback.io/doc/en/contrib/Long-term-support.html)).

I am closing this issue as "won't fix".
