### ISSUE TITLE
destroyById with undefined fk:ID issues destroyAll

### ISSUE THREAD

**Issue by temp3l** [strongloop/loopback-sdk-angular#112]
User.products.destroyById({id:1, fk:undefined}); 
and
User.products.destroyAll({id:1})

both send DELETE to /api/users/1/products

**Comment by jrschumacher** [comment]
@bajtos where can I find the method which strips out the keys with `undefined` values? Personally I'd either like an error thrown or convert `undefined` to `null`.

**Comment by bajtos** [comment]
@jrschumacher If the `fk` parameter is encoded in the request URL (sorry, don't have enough time to check it myself), then you need to look at Angular's ngResource: https://github.com/angular/angular.js/blob/v1.4.x/src/ngResource/resource.js#L448-L461

**Comment by bajtos** [comment]
To be honest, I think this issue is another good argument why we should drop ngResource and generate a client API that is more-or-less the same as the server API - see #133.
