### ISSUE TITLE
lint the generated code

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-sdk-angular#114]
Add a unit-test to run a linter (jshint, possibly also jscs) against the generated code.

**Comment by duffn** [comment]
This particular config shows 50 issues for a service I just generated. I know this is an old issue and would be happy to take on an update to get the generated code to conform.

**Comment by davidcheung** [comment]
Landed #218, npm test will now run eslint post unit-test. And double quote has been added as an exception for that file, given that often deployments will include minifying the code.
