### ISSUE TITLE
thenable functions (promise?)

### ISSUE THREAD

**Issue by slawo** [strongloop/loopback-sdk-angular#116]
Would id be possible to generate thenable functions for the models and instances instead of relying on callbacks?

The issue is not with callbacks but with the fact that most libraries written for angular expect promises or some any sort of thenable objects when passing data around.

Do you have any intention to add this type of compatibility?

**Comment by bajtos** [comment]
We are generating model classes based on ngResource which already supports promises OOTB. See the official Angular [documentation](https://docs.angularjs.org/api/ngResource/service/$resource) and also [Model resource API](http://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-ModelresourceAPI) in our docs.
