### ISSUE TITLE
Accessing all models from a directive/controller

### ISSUE THREAD

**Issue by slawo** [strongloop/loopback-sdk-angular#117]
Is there a way to access to all models through a special object containing all providers Instead of having to name each resource by name in the parameters. I have a few directives which should be able to retrieve data from a model depending on a parameter (modelName). These directives need to access to a model object containing all the individual models.
Is there a way to achieve this with the current version of loopback-sdk-angular?

**Comment by bajtos** [comment]
I believe this can be achieved by injecting `$injector` into your method and calling `$injector.get(modelName)`.
