### ISSUE TITLE
It must set value for the propety which not required while invoke the method in lb-services.js

### ISSUE THREAD

**Issue by xinshouke** [strongloop/loopback-sdk-angular#121]
I may call rest API without any value for that property which not required thr loopback explorer successfully.
 But when I invoke the same method in the lb-services.js under the client folder, I had to set all property including those values which not required in model, because only as this way, the record may added successfully.

**Comment by bajtos** [comment]
Could you please provide a (minimal) example how to reproduce your problem locally on my machine?

**Comment by bajtos** [comment]
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can provide instructions allowing us to reproduce the problem on our machines using the latest version.
