### ISSUE TITLE
Filter date on nested document

### ISSUE THREAD

**Issue by GameScripting** [strongloop/loopback-sdk-angular#123]
I am trying to filter my collection on nested date values, however I don't get any matches:

    Events.find({
      filter: {
        where: {
          'sensors.timeOpened' : { lt: dateFrom }
        }
      }
    })

dateFrom is a JavaScript Date object.
I also dont get any matches if I am using gt, gte or lte. However when using neq it matches all documents. When I try to filter with gt or lt on number fields the filter works as expected.
I've also checked the filter url param, it looks like expected:

    %7B%22where%22:%7B%22sensors.timeOpened%22:%7B%22lt%22:%222015-01-15T23:00:00.000Z%22%7D%7D%7D

I am using mongodb as a backend.
Any idea what the issue could be?

**Comment by GameScripting** [comment]
To overcome this problem on the angular site, I created a remote function. However the nodejs DB-Api behaves exactly the same way as the angular api does. May this be a general problem?
Any known limitations on filtering by date?

**Comment by nolandubeau** [comment]
Can you confirm if creating a remote function resolved the date filtering
issue or did not?

Thanks

On Sunday, January 18, 2015, Daniel Huhn <notifications@github.com> wrote:

> To overcome this problem on the angular site, I created a remote function.
> However the nodejs DB-Api behaves exactly the same way as the angular api
> does. May this be a general problem?
> Any known limitations on filtering by date?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback-sdk-angular/issues/123#issuecomment-70400583>
> .
>


-- 
Nolan Dubeau
VP, Engineering
Guardly

Sent from my Apple Newton

**Comment by GameScripting** [comment]
As I wrote on my second post, creating a remote function did not resolve my issue since the same "error" happens when using the DB api directly on the server.

If this is not an angular specific error, should I post the issue on another sub-project of loopback? On which?

**Comment by nolandubeau** [comment]
I would post to the loopback Google group as it could be a more generic
issue as opposed to angular.

On Sunday, January 18, 2015, Daniel Huhn <notifications@github.com> wrote:

> As I wrote on my second post, creating a remote function did not resolve
> my issue since the same "error" happens when using the DB api directly on
> the server.
>
> If this is not an angular specific error, should I post the issue on
> another sub-project of loopback? On which?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback-sdk-angular/issues/123#issuecomment-70408560>
> .
>


-- 
Nolan Dubeau
VP, Engineering
Guardly

Sent from my Apple Newton

**Comment by bajtos** [comment]
Please post the JSON file containing model definition. The suspicious part in your query is `sensors.timeOpened`, as that's not the correct way of testing nested properties AFAIK.

Can you try this instead? (It's just a wild guess.)

```
    where: {
      sensors: {
        timeOpened : { lt: dateFrom }
      }
    }
```

@raymondfeng What's the correct syntax for querying nested properties?

**Comment by bajtos** [comment]
Apparently LoopBack does not support filtering using nested properties yet - see https://github.com/strongloop/loopback/issues/517.  I am closing this issue as a duplicate.
