### ISSUE TITLE
undocumented dependency on ngResource

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-sdk-angular#126]
Whilst it is mentioned that lb-services comprises of some "Auto-generated AngularJS services, compatible with ngResource.$resource,", it isn't made particularly clear that ngResource is needed by lb-services.

If you don't grab the angular-resource scripts, you get a dependency injection error

**Comment by crandmck** [comment]
Added a note to http://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-Howitworks.  @jmls do you think that covers it?

**Comment by jmls** [comment]
looks much better ;) thanks

**Comment by crandmck** [comment]
ty!
