### ISSUE TITLE
User.getCurrent does not work at all

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback-sdk-angular#127]
It tries to GET:
/api/Users/:id with id=1

Sorry for not being verbose, but I hope it's clear enough :)

**Comment by bajtos** [comment]
What's wrong with `GET /api/Users/1`? What response are you getting back?

Please post full instructions how I can reproduce the problem on my machine.

**Comment by bajtos** [comment]
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can provide instructions allowing us to reproduce the problem on our machines using the latest version.
