### ISSUE TITLE
lb-ng-doc does not generate description of model

### ISSUE THREAD

**Issue by yurenju** [strongloop/loopback-sdk-angular#132]
STR:
1. use `slc loopback:model` generate a model `car`
2. edit car.json and add `description` field for model
3. generate lbServices.js by `lb-ng`
4. generate angular docs by `lb-ng-doc`

expected:
doc in comment of lbServices.js should contain description which add in (2)

actually:
only got the description like:
```
A $resource object for interacting with the Car model.
```

and the description is hard coding in [services.template.ejs](https://github.com/strongloop/loopback-sdk-angular/blob/b2b2d80c3e701a8fcaf5cb1a0a1d7c5480ecc452/lib/services.template.ejs#L30-L33)

**Comment by bajtos** [comment]
@yurenju can you contribute the enhancement yourself?
