### ISSUE TITLE
Generate isomorphic API

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-sdk-angular#133]
Almost all users new to LoopBack SDK for AngularJS get confused about the client API and the fact that the arguments must be passed in a named object. Figuring out how to correctly invoke related methods is even more difficult.

I am proposing to rework the code generator to drop ngResource and produce an API that is as much close to the server-side API as possible.

``` js
// server
Product.find({ where: { name: 'Pencil' } }, cb);

// AngularJS client
var promise = Product.find({ where: { name: 'Pencil' } });
// perhaps also
$scope.products = promise.$array;
```

Note that this is different from the solution proposed in #83. #83 is brining the whole loopback to the browser, while this is modifying the client API produced by our code generator.

/cc @seanbrookes @anthonyettinger @ritch @kraman What's your opinion? Would you prefer to have a client API that is closer to the server API, or do you prefer the current ngResource-based API instead?

Of course, the current ngResource-based API will remain available, the new isomorphic API will be released either as a new major version, or as a different template that can be chosen by the SDK user

---

Here is a (partial) list of issues and questions caused by this issue:
- #151 HasMany Relationship Storing same id for foreign key and primary key
- #47 how to pass filter/where argument to `find` and `findOne`
- #145 HasAndBelongsToMany relation Model.relationName.link() method not working as expected
- https://github.com/strongloop-internal/scrum-cs/issues/161 How to call findById for a related model from angular?
- https://github.com/strongloop-internal/scrum-cs/issues/51 Possible bug when updating model instance with updateAttributes in Angular
- https://github.com/strongloop/loopback-sdk-angular/issues/78#issuecomment-120340620 `link` methods must be called with extra argument
- #112 destroyById with undefined fk:ID issues destroyAll

**Comment by kraman** [comment]
Would this API have any advantages over the existing angular resource way of doing things? Perhaps make bi-dir sync easier?

**Comment by bajtos** [comment]
> Would this API have any advantages over the existing angular resource way of doing things?

It will be easier for new developers to learn. I was running a [LoopBack+Angular workshop](http://bit.ly/learn-loopback) twice and almost everybody got confused about the correct way of using the client API.

It is also a common source of confusion in the mailing list and gitter. People find a documentation page showing the server API and they don't realise they need a different API in the client. There are no warnings nor error messages to help them easily figure out their mistake.

> Perhaps make bi-dir sync easier?

No, you need the full loopback app for offline sync, at least at the moment. See #83 for that.

**Comment by kraman** [comment]
@jasonaden @bajtos I can see the advantage of this proposal, but if size is the major concern in the #83, I'm wonder if it makes sense to try and optimize that bundle and automatically get all the advanced LB features. Specially considering something like http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

**Comment by bajtos** [comment]
> @kraman if size is the major concern in the #83, I'm wonder if it makes sense to try and optimize that bundle and automatically get all the advanced LB features.

See https://github.com/strongloop/loopback/issues/989#issuecomment-86418557. I don't think it's possible to reduce the size of the browserified bundle to a similar order of magnitude that can be achieved with a thin code-generated client. Just four core files (dao, datasource, relation-definition, persisted-model) contain ~250kb of un-minified source code, not including any dependencies.

Having said that, reducing the size of browserified bundle is still important, regardless on the decision made about the proposal discussed here.

> @jasonaden That being said, the documentation is pretty bad and it's hard to determine what methods take as their parameters. 

Are you referring to the ngdoc comments generated by the code generator, which can be viewed e.g. using docular via `lb-ng-doc`? How can we improve these comments to make it more clear what are method arguments?

> I've been using it for a few weeks and I'm still not quite sure the right way to call a .link() function between two HasManyThrough relation objects.

I think you have run into a known issue, see https://github.com/strongloop/loopback-sdk-angular/issues/78.

**Comment by glesage** [comment]
Thanks for all solutions!

FYI, the reason why @mikamboo 's solution in https://github.com/strongloop/loopback-sdk-angular/issues/145 works is because passing `null` removes the `id` parameter that gets automatically passed to any request...

Ex: `Car.tags.link({id:carID, fk:tagID}, null)`
Would actually create a TagCars row in the datasource as such: `id: carId, carId: carId, tagId: tagId`

**Comment by bajtos** [comment]
Considering recent development, where AngularJS 1.x have been superseded by Angular 2+, and LoopBack 2.x/3.x is going to be superseded by LoopBack 4 (a.k.a Next), I don't see how this will ever become a priority for us. I am closing this issue.

If there is anybody interested in making this happen, then I think the best option is to fork this repository and create a new npm package.
