### ISSUE TITLE
link method not attaching fk to url, failing to create relationship

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [strongloop/loopback-sdk-angular#135]
Related to this issue: https://github.com/strongloop/loopback-sdk-angular/issues/78

Still I am trying to do the workaround of passing null, empty, duplicate object to the link method but it is not working.

Here is my code:

`.MallBranch.customPromotions.link({
              id: item.id,
              fk: promotionAfterCreation.id
            }, null);`

or even

`.MallBranch.customPromotions.link({
              id: item.id,
              fk: promotionAfterCreation.id
            }, {
              id: item.id,
              fk: promotionAfterCreation.id
            });`

or even more

`.MallBranch.customPromotions.link({
              id: item.id,
              fk: promotionAfterCreation.id
            },{
              mallBranchId: item.id,
              customPromotionId: promotionAfterCreation.id
            });`

Always gives me an error in the browser console:

`PUT http://localhost:3000/api/MallBranches/55027ad139cb44c8431e4e83/customPromotions/rel 404 (Not Found)`

any solutions please?

**Comment by bajtos** [comment]
@ahmed-abdulmoniem the issue #78 is not fixed yet, that's why the `link` method does not work for you.

I am closing this issue as a duplicate.
