### ISSUE TITLE
Convenience method to update attributes of an instance

### ISSUE THREAD

**Issue by ilianaza** [strongloop/loopback-sdk-angular#136]
Based on the answer in the https://github.com/strongloop/loopback-sdk-angular/issues/134 I was thinking to introduce a helper method that would automate the process of removing id property from the instance before all attributes are updated. This helper method would look something along these lines inside Resource generator:

``` javascript
...
'updateProps': {
  url: urlBase + '/events/:id',
  method: 'PUT',
  transformRequest: function(data) {
    delete data.id;
    return angular.toJson(data);
  }
}
...
```
1. Please let me know if something along these lines already exists and I'm reinventing the wheel here.
2. What's the best way to implement this convenience method and name it?
3. What are the potential pitfalls of this approach?

**Comment by bajtos** [comment]
I'd much rather fix the connectors to correctly detect whether the id value is being modified or not, see my comment in #134.

> 1. Please let me know if something along these lines already exists and I'm reinventing the wheel here.

You can use `updateOrCreate`, but that has slightly different semantics. We don't have a direct equivalent of your proposed method.

> What's the best way to implement this convenience method and name it?

Well, if `updateAttributes` rejects request with an id property, then it's best to add the `transformRequest` option directly to `updateAttributes`.

> What are the potential pitfalls of this approach?

IMO you should not change the `data` object passed in as an argument. This works for me in Node, though it may not work the same way in old browsers like IE8:

```js
var data = Object.create(data);
data.id = undefined;
// data.id will be excluded from the JSON now
```

**Comment by bajtos** [comment]
It seems to me the discussion here has reached a dead end, I am going to close this issue. Feel free to reopen if you disagree!
