### ISSUE TITLE
Improving documentation for loopback angular sdk page

### ISSUE THREAD

**Issue by robinskumar73** [strongloop/loopback-sdk-angular#137]
#### Referring to [Angular Sdk Docs](http://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK)
**"Handling 401 Unauthorized"**
There has been given a method for  LoopBack server fail with **401 errors** for which it needs to be improved.

##### Posted code in docs
    // Inside app config block 
    $httpProvider.interceptors.push(function($q, $location) {
      return {
        responseError: function(rejection) {
          if (rejection.status == 401) {
            $location.nextAfterLogin = $location.path();
            $location.path('/login');
          }
          return $q.reject(rejection);
        }
     };
   });

Here a slight improvement needs to be done in this page i.e. is server fails with 401 error then it will try to go to "/login" page.
But client will always show  
User.IsAuthenticated()  // outputs true because client has no information that the token has expired.
Thus we need to clear Session and localStorage first before redirecting to "/login" page for safe login.

###### This code is less error prone and will work always
```
    $httpProvider.interceptors.push(function ($q, $location, LoopBackAuth) {
        return {
            responseError: function (rejection) {
                if (rejection.status === 401) {
                    //Now clearing the loopback values..
                    LoopBackAuth.clearUser();
                    LoopBackAuth.clearStorage();
                    $location.nextAfterLogin = $location.path();
                    $location.path('/login');
                }
                return $q.reject(rejection);
            }
        };
    });
```

**Comment by bajtos** [comment]
Thank you for the suggestion. Please contribute the change directly to the documentation, see [Contributing to LoopBack documentation](http://docs.strongloop.com/display/LB/Contributing+to+LoopBack+documentation).
