### ISSUE TITLE
Include filter post issue

### ISSUE THREAD

**Issue by MikeSpock** [strongloop/loopback-sdk-angular#140]
These two lines do de same thing.

            $scope.list = Todo.find({"filter[include]": 'owner'});
            $scope.list = Todo.find({filter:{include: "owner"}});

Docs suggest using the second version, but still, the first one sends a good request. I console.log the arriving ctx variable on a remote hook, and I get this for `context.req.query`:

    { filter: { include: 'reward'}}
    { filter: '{"include":"reward"}' }

The first appears to be right.  This seems like a bug in angular sdk generator.

**Comment by bajtos** [comment]
I don't understand. Are you saying that `Todo.find({filter:{include: "owner"}});` does not work correctly?

**Comment by davidcheung** [comment]
Hi @MikeSpock, hope this is no longer an issue for you, closing this issue as it has been stale for over a year, [please reopen](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) if you see fit.
