### ISSUE TITLE
user.$logout() does not work

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback-sdk-angular#143]
if I create a new AppUser (derived from User) with id=1 called user, I get errors logging out with user.$logout():

POST http://192.168.1.102:8100/api/AppUsers/logout?id=1 500 (Internal Server Error):

Model::findById requires the id argument

I am using sdk version 1.3.7

**Comment by bajtos** [comment]
You need to call `User.logout()` instead of `user.$logout()`. Also note that a newly created user is not logged in by default, you have to call `User.login` first.

**Comment by adanielyan** [comment]
I have a SystemUser model that is inherited from User.

When I try to logout in my API explorer I get this error:
```
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Model::findById requires the id argument",
    "stack": "Error: Model::findById requires the id argument\n    at /var/www/jjform/node_modules/loopback-datasource-juggler/lib/dao.js:741:10\n    at /var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at /var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at process._tickDomainCallback (node.js:486:13)\n    at process.<anonymous> (/var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)"
  }
}
```

Can't figure out what I am doing wrong.

**Comment by adanielyan** [comment]
Moved my question to loopback issue queue.

https://github.com/strongloop/loopback/issues/1531
