### ISSUE TITLE
Can not find 'LoopBackResource' and 'LoopBackAuth' provider.

### ISSUE THREAD

**Issue by piotrvladimir** [strongloop/loopback-sdk-angular#148]
Hi Support team.
I've generated loopback services but can not get find LoopBackResource and LoopBackAuth provider.
Where can I find these providers?

**Comment by bajtos** [comment]
Did you add the generated script file to your application and include `lbServices` as a dependency of your app?

**Comment by richardpringle** [comment]
Hey @piotrvladimir, did you ever resolve this? I am going to close for now but **please re-open if** you did as @bajtos suggested and something still isn't working!
