### ISSUE TITLE
Right way to fetch related models for nested ng-repeat using lb-services

### ISSUE THREAD

**Issue by gautamkishore** [strongloop/loopback-sdk-angular#149]
how can i fetch the json data of related model of a service. Suppose i have a transactions and accounts model and a transactions model has relation with accounts model. I want to display the data of Transactions model with all related accounts data for that transaction.

**Comment by bajtos** [comment]
```js
Transaction.accounts({ id: transaction.id });
```

See the API documentation in the file you have generated using our SDK and/or the hosted API docs for [User.accessTokens()](http://apidocs.strongloop.com/loopback-sdk-angular/#user-accesstokens-1).
