### ISSUE TITLE
lb-ng-doc command Error

### ISSUE THREAD

**Issue by husseiny-m** [strongloop/loopback-sdk-angular#150]
Hi,

When I try to generate the documentation of the lbServices.js I get the following error:
 [Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT]

-------- verifying plugins --------
-------- generating Docs --------
Extracting loopback Docs For Section "lbServices"...
-------- generating partials directories for groups --------
-------- generating partials directories for sections --------
-------- merging child docs with parent docs --------
-------- generating partials --------
Generating support files
Generating webapp partials
Generating config partials
Generation complete
-------- generating index.html page --------
-------- gathering all doc_api, plugin, and configured css and js --------
-------- generating report --------
DONE! Generated 35 pages in 2193 ms. Partials per second : 16

Browse the documentation at http://localhost:3030/
 { [Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\WINDOWS\\system32\\cmd.exe',
  path: 'C:\\WINDOWS\\system32\\cmd.exe',
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "node C:\\Users\\Husseiny\\AppData\\Roaming\\npm\\node_modules\\loopback-sdk-angular-cli\\node_modules\\docular\\lib\\nodeserver\\server.js 3030"' }

Please help.
Thanks

**Comment by bajtos** [comment]
Hi, thank you for reporting this issue. I am afraid the docular module we use for rendering API docs is rather broken on Windows :( Rather than trying to fix a something that may be impossible to fix, I'd like to rework `lb-ng-doc` to use our strong-docs tools which powers http://apidocs.strongloop.com.

I am closing this issue in favour of #22.

**Comment by bajtos** [comment]
Edit: in favour of https://github.com/strongloop/loopback-sdk-angular-cli/issues/22
