### ISSUE TITLE
"Expected response to contain an object but got an array" in Many-to-Many relationship

### ISSUE THREAD

**Issue by anhtuan9113** [strongloop/loopback-sdk-angular#152]
Hi Support team,
- I have two models Artist, Event and their relationship is Many-to-Many. 
- I try to use Artist.events.findById() function to get all events of an artist. Http response status is 200 but angular throws an error "Error in resource configuration for action `::findById::Artist::events`. Expected response to contain an object but got an array".

Could you help me to check it ?
Thank you so much!

**Comment by jonathan-casarrubias** [comment]
Try with

```javascript
Artist.events({
    id: artist_id
});
```

You can also add filters

```javascript
Artist.events({
    id: artist_id,
    filter: {
        where: {
             startAt : date
        }
    }
});
```

Cheers
Jon

**Comment by davidcheung** [comment]
Hi @anhtuan9113 , hope jonathan-casarrubias's answer solved your question, the [include filter](https://docs.strongloop.com/display/public/LB/Include+filter) and [where filter](https://docs.strongloop.com/display/public/LB/Where+filter) could be useful.

Unfortunately we only accept `feature requests` and `bug reports` on Github Issues, if you still have questions please refer to [this link](https://github.com/strongloop/loopback/wiki/Questions).

Thanks!
