### ISSUE TITLE
ReferencesMany relationship from Angular SDK makes incorrect REST call?

### ISSUE THREAD

**Issue by dlutz2** [strongloop/loopback-sdk-angular#158]
Given a model of  Story -> referencesMany -> Events , 
calling Story.find() works correctly but when calling Story.events(123), the call that actually is made to the REST service is
   **/api/stories/events**
    but shouldn't  it be
   **/api/stories/123/events**

API Explorer makes the correct call and receives the expected response.
Any idea why this might be?
thanks

  dave

**Comment by xixilive** [comment]
When use a relation method, your should specify a primary key and a foreign key. In case above, Story.events is a relation, you may call it with {id: STORYID}

**Comment by davidcheung** [comment]
Hi @dlutz2, hope @xixilive's answer solved your question, the [include filter](https://docs.strongloop.com/display/public/LB/Include+filter) and [where filter](https://docs.strongloop.com/display/public/LB/Where+filter) could be useful

not sure if I am understanding your scenario properly but this might also be helpful
```
Story.findById({
    filter: {
        include: ["events"]
    },
    id : 123
})
```
Unfortunately we only accept `feature requests` and `bug reports` on Github Issues, if you still have questions please refer to [this link](https://github.com/strongloop/loopback/wiki/Questions).

Thanks!
