### ISSUE TITLE
LoopbackAuth & User for third party authentication

### ISSUE THREAD

**Issue by dthib** [strongloop/loopback-sdk-angular#164]
Hi,

I am trying to use Loopback with AngularJS and to have a third party authentication with passport. I have seen in some posts that it is not entirely supported by loopback-sdk-angular for now. Is that right? If I need to do it by myself, is there any recommendation? In particular, I am a bit confused with the differents services: LoopbackAuth that has some useful methods, User that calls sometimes LoopbackAuth (e.g. logout). I am wondering also If I should use cookies or token. Any input will be appreciated!

Thanks,
Best regards,
Thibaut

**Comment by xixilive** [comment]
Since loopback provides an Restful API service, Each request are authenticated via an access token. and LoopbackAuth is a client-side implementation for the server-side authentication.

**Comment by davidcheung** [comment]
Hi @dthib, I believe third-party-integrations would be more likely to be implemented on the server-side as it will consist of you `app_id` and `app_secret` depending on the services, [loopback-component-passport](https://github.com/strongloop/loopback-component-passport) or [loopback-component-oauth2](https://github.com/strongloop/loopback-component-oauth2) might be helpful for your implementation, and we only accept feature requests and bug reports on github, if you have further question please refer to [this link](https://github.com/strongloop/loopback/wiki/Questions). 
Thanks!
