### ISSUE TITLE
Add minify option to generator

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback-sdk-angular#166]
While I am aware this is something that can be handled externally (I do it with Gulp), it might be useful to have a CLI option that generates a minified version of the SDK, along with a regular one. Some projects may not be using gulp, and giving them an option for immediate deployment of a minified SDK would be a boon.

**Comment by davidcheung** [comment]
@csvan looking at old open issues,  
I wasn't aware of this before but the same issue is addressed by the [`gulp-loopback-sdk-angular`](https://github.com/strongloop/gulp-loopback-sdk-angular) module

you mentioned you already had an alternative solution to this, but just for your reference you could probably do something such as this, following the `gulp-loopback-sdk-angular` 

```bash 
npm install --save gulp-minify
```

```js
var gulp = require('gulp');
var rename = require('gulp-rename');
var minify = require('gulp-minify');
var loopbackAngular = require('gulp-loopback-sdk-angular');

gulp.task('default', function () {
    return gulp.src('./server/server.js')
    .pipe(loopbackAngular())
    .pipe(rename('lb-services.js'))
    .pipe(minify())
    .pipe(gulp.dest('./client/scripts'));
});
```

I'm closing the issue now. Thanks for bring this up!
