### ISSUE TITLE
Moment.js: UTC dates get corrupted

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback-sdk-angular#167]
I use moment.js in order to get the start and end dates of the current day, in order to search for events that occur on it:

```
var date = moment().utc();

MyAmazingLoopbackService.find(
{
    filter: {
        where: {
            and: [
                   {createdAt: {gte: date.startOf('day').toDate()}},
                   {createdAt: {lte: date.endOf('day').toDate()}}
            ]
        }
    }
},
// .....
```

If I console.log either of the start or end dates above, they show the correct values:

```
console.log(date.startOf('day').toDate()); // Mon Jul 20 2015 02:00:00 GMT+0200 (CEST)
console.log(date.endOf('day').toDate()); // Tue Jul 21 2015 01:59:59 GMT+0200 (CEST)
```

However, inspecting the data that is actually sent to the server, it turns out the Angular SDK turn the dates into the following:

```
{
    "where": {
         "and": [
               {"createdAt": {"gte": "2015-07-20T23:59:59.999Z"}}, 
               {"createdAt": {"lte": "2015-07-20T23:59:59.999Z"}}
          ]
     }
}
```

IOW the date information gets erased and both values are flattened down to the same time. Is this expected behavior?

**Comment by davidcheung** [comment]
hi @csvan, sounds like a bug, would you know if this issue happens only with `utc()` or any `dates`? or it is an issue with angularSDK parsing `where filter` on just datatype `Date`?, would you be able to create a sample repo to [reproduce the issue](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report)?
Thanks

**Comment by csvan** [comment]
@davidcheung - I forgot about this issue actually :) It is not a problem with Loopback, but my code. The reason this happens is that the startOf and endOf methods are mutating, and hence both passed dates correspond to the value of the last call to endOf.
