### ISSUE TITLE
Expose getter method for urlBase

### ISSUE THREAD

**Issue by emgeee** [strongloop/loopback-sdk-angular#169]
It would be nice to be able to be able to retrieve the `urlBase` from the generated `lbService` module for the occasional times when querying routes using the standard `$https` service is necessary.

I'm thinking a `getUrlBase()` method on the `LoopBackResource` provider.

**Comment by davidcheung** [comment]
Looks like this [feature](https://github.com/strongloop/loopback-sdk-angular/commit/b3a7c2608c61fbb72b5afa5a82545f15b9d58867) has been added now 

Closing issue.
