### ISSUE TITLE
Method link() sends incorrect id param

### ISSUE THREAD

**Issue by ilya-khaustov** [strongloop/loopback-sdk-angular#170]
When using `link()` like this:

    Company.categories.link({id: $scope.company.id, fk: category.id})

I had an error in response saying that relation key is duplicated. After changing loopback-sdk service  from:

         "::link::Company::categories": {
            params: {
             'fk': '@fk',
             'id': '@id'
            },
            url: urlBase + "/Companies/:id/categories/rel/:fk",
            method: "PUT"
        },

to:

         "::link::Company::categories": {
            params: {
             'fk': '@fk',
             'pk': '@pk'
            },
            url: urlBase + "/Companies/:pk/categories/rel/:fk",
            method: "PUT"
        },

I managed to successfully add relation with a following method call:

    Company.categories.link({pk: $scope.company.id, fk: category.id})

Looks like sending id in request body is not a good idea when creating relations. The better decision is to prevent id from being added to request body rather than changing its name. Any ideas?

**Comment by ernie58** [comment]
I'm having this issue to.
Currently I work around it by adding an extra id parameter in the request body:

`Company.categories.link({id: $scope.company.id, fk: category.id}, {id: 0})`

Strangely, not all of my models have this problem when linking them. I'm trying to see why they behave differently, but I can't find anything at first sight

**Comment by ernie58** [comment]
This works also: 
`Company.categories.link({id: $scope.company.id, fk: category.id}, null)`

After further investigating, I have the problem in all of my models.
I'm using grunt-loopback-angular-sdk (which uses loopback-angular-sdk 1.4.1)
When I look in my generated service I don't have the id parameter, only the fk:

    params: {
         'fk': '@fk'
        },

What version of the generator are you using, @ilya-khaustov ?

**Comment by ilya-khaustov** [comment]
@ernie58 `npm show loopback-sdk-angular` shows that version is 1.5.0.

**Comment by ernie58** [comment]
That could be why I don't see the id-parameter

**Comment by ilya-khaustov** [comment]
@ernie58 No, I guess this version is OK. I rerun `lb-ng` command just now and the original faulty snippet is not present in the generated code. Issue can be closed by now, however it stays a mystery whether somebody fixed it or it was my models configuration failure.

**Comment by davidcheung** [comment]
Glad to hear issue is resolved, please raise the issue again if you run into it in the future, closing ticket :)
