### ISSUE TITLE
LoopBackAuth.rememberMe always resolving to true

### ISSUE THREAD

**Issue by njcaruso** [strongloop/loopback-sdk-angular#171]
Per the [documentation](https://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-Authentication) I'm logging in below:
```
      User.login({
          username: data.email,
          password: data.password,
          rememberMe: data.rememberMe
        });
```
if rememberMe is set to `false` in the login call, it resolves to `true` in the lb-service interceptor after login. 

The code for the interceptor is:
`LoopBackAuth.rememberMe = response.config.params.rememberMe !== false;`

However, `response.config.params.rememberMe` resolves to undefined, resulting in the value 
rememberMe to resolve to `true`.

Changing the code to use `data` instead of `params` works.

`LoopBackAuth.rememberMe = response.config.data.rememberMe !== false;`

**Comment by davidcheung** [comment]
hi @njcaruso 
Passing `parameters` and `credentials` in 2 separate parameters should solve your issue, and undefined does default to `true` 
[Login functions docs](https://apidocs.strongloop.com/loopback-sdk-angular/#user-login)
```
var params = { rememberMe: $scope.rememberMe };
var credentials = {
  email: data.email,
  password : data.password
};
User.login(params, credentials);
```

Hope this solves your issue

**Comment by davidcheung** [comment]
@njcaruso, I hope the above solution solved your issue, Closing this ticket, if you feel like this is a bug  or I misunderstood what you were saying please reopen ticket. You can also use our [Google groups](https://groups.google.com/forum/#!forum/loopbackjs) to ask questions :)

**Comment by njcaruso** [comment]
Thanks!
