### ISSUE TITLE
Model.destroyAll not exposed by SDK.

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback-sdk-angular#174]
This method is present by default on the server-side, but does not get exposed by the SDK. Might be wrong, but I think it is the only default method which is not present in the SDK.

**Comment by bajtos** [comment]
Hi @csvan, the method `Model.destroyAll` is not exposed via REST API by default because we consider it as rather dangerous. Once you enable it (see e.g. https://github.com/strongloop/loopback/issues/491#issuecomment-116833323), you should re-generate your Angular client to get the method included.

**Comment by bajtos** [comment]
I think it would be good to include this info in the documentation:
 - why `destroyAll` is not available via REST API by default
 - how to expose it

**Comment by csvan** [comment]
@bajtos I agree that it is dangerous, but IMO that judgment call should be left to devs to make. First and foremost, I think devs expect a consistent API, which they can then configure to whatever degree their security and other needs may be.

**Comment by crandmck** [comment]
The fact that the endpoint is not exposed by default is documented in http://loopback.io/doc/en/lb3/PersistedModel-REST-API.html#delete-all-matching-instances

**Comment by sleroy** [comment]
Yet the documentation does not provide how to expose it. Any reference ? the sharedClass trick is not working (NPE)

**Comment by bajtos** [comment]
@sleroy 
> Yet the documentation does not provide how to expose it. Any reference ? the sharedClass trick is not working (NPE)

See here: https://github.com/strongloop/loopback/issues/491#issuecomment-116833323

> You should be able to set up the remoting in your model class as follows:

``` js
MyModel.remoteMethod('destroyAll', {
    isStatic: true,
    description: 'Delete all matching records',
    accessType: 'WRITE',
    accepts: {arg: 'where', type: 'object', description: 'filter.where object'},
    http: {verb: 'del', path: '/'}
  });
```

I'd personally recommend to create a custom remote method (see the [docs](https://loopback.io/doc/en/lb2/Remote-methods.html#how-to-define-a-remote-method)) that will verify the `where` argument to avoid accidental deletion of all model instances and call `destroyAll` under the hood.

Would you like to contribute a patch to improve our documentation? Here are the instructions to get you started: http://loopback.io/doc/en/contrib/doc-contrib.html
