### ISSUE TITLE
bulkUpdate method is missing

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback-sdk-angular#182]

**Comment by davidcheung** [comment]
Hi @rkmax, I believe the `updateAll` method might be what you were looking for,
documentations can be launched upon the generated services via `lb-ng-doc <path-to-lb-services.js>` for models you've created via docular ,

If I understand your problem correctly I believe you can achieve what you want by using `updateAll` with the `where` filter, [see more about where filter](https://docs.strongloop.com/display/public/LB/Where+filter)

```
updateAll(parameters, postData, successCb, errorCb)

Update instances of the model matched by where from the data source.

Parameters

parameters(optional) – {Object=} – Request parameters.
where – {object=} - Criteria to match model instances
postData – {Object} – Request data. This method expects a subset of model properties as request parameters.
successCb(optional) – {function(Object,Object)=} – Success callback with two arguments: value , responseHeaders .
errorCb(optional) – {function(Object)=} – Error callback with one argument: httpResponse .
Returns

{Object} – An empty reference that will be populated with the actual data once the response is returned from the server. This method returns no data.
```

Hope this answers your question :)

**Comment by rkmax** [comment]
@davidcheung I dont think so. because .updateAll() does the same change for every record that match the criteria but [bulkUpdate](https://apidocs.strongloop.com/loopback/#persistedmodel-bulkupdate) performs a list of updates. I need the second behavior

**Comment by davidcheung** [comment]
@rkmax you're right, I will add the feature tag to it, in the mean while not sure if [this approach](https://github.com/strongloop/loopback/issues/491#issuecomment-116833323) can be a work-around.

**Comment by johannesjo** [comment]
+1

**Comment by bajtos** [comment]
The method `bulkUpdate` is hidden from the REST API unless the model settings enable one of the following flags: `trackChanges` or `enableRemoteReplication`.

My recommendation is to use `enableRemoteReplication`, which only exposes additional REST endpoints. The other flag `trackChanges` starts tracking of all changes, which requires additional database setup and incurs non-negligible performance cost.

```json
{
  "name": "MyModel",
  "base": "PersistedModel",
  "enableRemoteReplication": true,
  "properties": {
  }
}
```
