### ISSUE TITLE
Optionally disable console errors

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-sdk-angular#186]

**Comment by davidcheung** [comment]
Hi @gausie 
Can you clarify about optionally disabling console errors, 
are you referring to HTTP errors from the ajax calls? 
the CRUD methods services call, AFAIK the methods are called via [`$ngResource`](https://docs.angularjs.org/api/ngResource/service/$resource#example) of Angularjs
which then throws regular 
if not would you be able provide more details of your feature request?

**Comment by gausie** [comment]
I'm referring to the `console.error`s in the code.

For example https://github.com/strongloop/loopback-sdk-angular/blob/master/lib/services.js#L144

**Comment by BoLaMN** [comment]
+ 1 

I'd suggest switching them to debug as not all of the logs are errors and seem to flood the console if you have a few end points disabled.

**Comment by bajtos** [comment]
Makes sense. Would you like to contribute this change yourself? See http://loopback.io/doc/en/contrib/index.html to get started.

**Comment by bajtos** [comment]
With the release of LoopBack 4.0 GA (see the [announcement](https://strongloop.com/strongblog/loopback-4-ga)), this SDK has entered Active LTS mode which means we are no longer accepting new features (see our [LTS policy](https://loopback.io/doc/en/contrib/Long-term-support.html)).

I am closing this issue as "won't fix".
