### ISSUE TITLE
Date format is subtracted by one day

### ISSUE THREAD

**Issue by chule143** [strongloop/loopback-sdk-angular#196]
When a date is received from the backend, is received correctly, but when it's parsed in angular is substracted by one day:

```javascript
$scope.test1 = new Date('2014-01-01T00:00:00Z'); // data from loopback
$scope.test2 = '2014-01-01T00:00:00Z'; // data from loopback
$scope.test3 = new Date('2014-01-01 00:00:00'); // sample date
```

```html
{{ test1 | date: 'MM dd, yyyy'}} -> 12 31, 2013
{{ test2 | date: 'MM dd, yyyy'}} -> 12 31, 2013
{{ test3 | date: 'MM dd, yyyy'}} -> 01 01, 2014
```
[Fiddle](http://jsfiddle.net/jby6Lanp/1/)

**Comment by davidcheung** [comment]
Hi @chule143 

This is actually a javascript behavior, when you declare the date it has no timezone concept, but browser interprets it with the concept of timezone. [See this example](http://jsfiddle.net/z4an9w3n/).
Hope this helps, 

Not sure changing our default behavior is a good idea, it could be a future thing to add option to handle timezone(changing the format via passed in `options`?), so the integration with angular-sdk is more seamless.

@chule143 maybe you can bring this up as a discussion in the [google-groups](https://groups.google.com/forum/#!forum/loopbackjs)

@bajtos any thoughts?

**Comment by chule143** [comment]
Hi @davidcheung,

Thank you for your answer :) , this is the link in the google group:

[https://groups.google.com/forum/#!topic/loopbackjs/1bLR_HMHzkA](https://groups.google.com/forum/#!topic/loopbackjs/1bLR_HMHzkA)

**Comment by davidcheung** [comment]
Closing issue now, can discuss further on google groups :)
