### ISSUE TITLE
clear logged in user if logout fails

### ISSUE THREAD

**Issue by martinjuhasz** [strongloop/loopback-sdk-angular#197]
i came across the following situation:

i logged in successfully as a user using `User.login()` on the client side. After some time, the access token got wiped from the server side. on the client side the user still had it's old access token stored locally and made requests with that (that now all failed ofc). 
Now if the user clicks the logout link, calling `User.logout()`, fails in an 500 error from the server saying "token not found". This is okay since that token doesn't exist but shouldn't that also clear my login from the client side?

to fix that i wrote the following on my logout method:
```javascript
User.logout().$promise.then(function() {
      $state.go('login');
    }).catch(function(error){
      LoopBackAuth.clearUser();
      LoopBackAuth.clearStorage();
      $state.go('login');
    });
```

Shouldn't the `clearUser()` and `clearStorage()` method also be called if the logout fails because of the missing token or is there another mechanism to clear the user from local storage if he has no active session?

thanks in advance

**Comment by davidcheung** [comment]
@martinjuhasz thanks for bring this up, I'm actually not sure whether logout 500 should trigger a client side to `clearUser() and clearStorage()`, or maybe `token not found` should not throw `500`? or both? But I agree that something should be improved in this scenario. 
@bajtos any thoughts?

**Comment by mrbatista** [comment]
@martinjuhasz @davidcheung [This](https://github.com/strongloop/loopback-sdk-angular/pull/178/files) pull request solves the problem. Any response of method `logout` must clear token and userId in storage. I need a few minutes to write a test unit before @bajtos merges.

**Comment by davidcheung** [comment]
Thanks @mrbatista! Will close issue once this is merged.

**Comment by martinjuhasz** [comment]
nice. thank you all!

**Comment by davidcheung** [comment]
Thanks @mrbatista!
@martinjuhasz I believe this is now fixed via https://github.com/strongloop/loopback-sdk-angular/commit/4dcf971c55b44cfe820d57a2ccfddfce7f04600c
Closing issue now, please reopen it if this remains an issue
