### ISSUE TITLE
CommonJS and es6 module support

### ISSUE THREAD

**Issue by dfeddad** [strongloop/loopback-sdk-angular#200]
I usually use Browserify and Webpack to bundle my code and find it very useful if the generated module can allow the use of CommonJS package manager and ES6 modules.

```js
import lbServices from './lb-services';

angular.module('app', [lbServices]);
```

**Comment by 0candy** [comment]
Would you like to submit a patch?

**Comment by dfeddad** [comment]
@0candy I submitted a pull request. Please check https://github.com/strongloop/loopback-sdk-angular/pull/201

**Comment by 0candy** [comment]
Thank you for your pull request. We will review it and get back to you.

**Comment by davidcheung** [comment]
Closing issue as PR is landed
