### ISSUE TITLE
Where is my documentation?

### ISSUE THREAD

**Issue by jmkgreen** [strongloop/loopback-sdk-angular#205]
I have followed what appears to be the "Loopback way" and documented my model with a description in the `model.json` file.

I can see this description in the API Explorer, but not within the lbServices file so I now have a developer producing the client who rightly complains that he has no idea what's what.

Am I doing something wrong..?

**Comment by davidcheung** [comment]
Hi @jmkgreen, sorry for the late response, is this still an issue for you? I would have thought https://github.com/strongloop/loopback-sdk-angular/pull/191 would have dealt with this issue

**Comment by davidcheung** [comment]
Or maybe if you were talking about docular, is was removed from the code, we are looking to use `strong-docs` instead, to track this issue please refer to https://github.com/strongloop/loopback-sdk-angular-cli/issues/22

Closing this issue now, please feel free to reopen if you see fit. Thanks
