### ISSUE TITLE
$save uses upsert and sends id as a get parameter

### ISSUE THREAD

**Issue by sespinosa** [strongloop/loopback-sdk-angular#211]
Im trying to edit user attributes in this way 

```
Client.getCurrent(function(user){
  user.full_name = 'This is my test full name';
  user.$save();
});
```

The problem is, the request its being made to

http://localhost:3000/api/Clients?id=3

I was checking the generated service and the $save method uses upsert even if the instance exists in the datasource.

So upsert sends the id as a get param and loopback cant resolve that (idk), and responds with 401,

But if i change the ?id=3 for a /3 as in

http://localhost:3000/api/Clients/3

everything works, the temp fix for this is using **prototype$updateAttributes**.

A posible solution for this is making the $save method check for the id, if exists makes the call as /:id, if not sends all the params in the same way as usual (because in a new object you dont need to set the id attribute, it gets generated in the create process).

**Comment by richardpringle** [comment]
related to #134 <- (I think)

**Comment by richardpringle** [comment]
@sespinosa are you using mongoDB?

**Comment by sespinosa** [comment]
@richardpringle yes, im using mongodb.

**Comment by richardpringle** [comment]
@davidcheung, so it looks like #134 is related and that it hasn't been resolved... you want to take over?

**Comment by davidcheung** [comment]
Hi @sespinosa, have you tried the work-around suggested here https://github.com/strongloop/loopback-sdk-angular/issues/134#issuecomment-81992967? it looks like its the same issue as #134, going to close this and track bug there as theres more information there. Please reopen the issue if you see fit or if I misunderstood your issue (in that case please reopen and would be helpful if you could provide a [sandbox](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) of the bug),Thanks
