### ISSUE TITLE
BUG:  User#getCurrent does not handle error

### ISSUE THREAD

**Issue by anagrath** [strongloop/loopback-sdk-angular#212]
Reproduce steps:
1.) Login with a user
2.) Go directly to DB and remove access token for that user
3.) Go to secure page and print isAuthenticated

Expected: isAuthenticated should be false
Actual: isAuthenticated is true

The issue can be resolved fairly easily.  The currentUserData is null because authentication fails from server side.  If currentUserData is null, we should clear the currentUserId so that isAuthenticated becomes false.

See generated code:
```
        "getCurrent": {
           url: urlBase + "/Users" + "/:id",
           method: "GET",
           params: {
             id: function() {
              var id = LoopBackAuth.currentUserId;
              if (id == null) id = '__anonymous__';
              return id;
            },
          },
          interceptor: {
            response: function(response) {
              LoopBackAuth.currentUserData = response.data;
              return response.resource;
            }
          },
          __isGetCurrentUser__ : true
        }
      }
    );
```

**Comment by davidcheung** [comment]
Hi @anagrath,  can you take a look to see if https://github.com/strongloop/loopback-sdk-angular/commit/4dcf971c55b44cfe820d57a2ccfddfce7f04600c resolves your issue?

**Comment by anagrath** [comment]
Will do. I am out of the office. Will take a look on Tuesday the 17th.

**Comment by davidcheung** [comment]
Thanks! @anagrath

**Comment by anagrath** [comment]
Hi David,

I am not sure it does resolve the issue.  The issue I am having does not deal with an error on logging out, but rather on getting the current user.  The use case that is failing is that when an access token is expired, the system is still reporting as though the user is logged in.  I believe I traced it back to the get current user function — if there is an error here we should clear the cached user.

However, I think you may be asking if the same code would resolve the issue if it were added for get current and I believe it is true that it would.

Thank you for looking into this and I hope that this info will help bring the issue to a conclusion quickly.

Aditya

**Comment by mrbatista** [comment]
Add interpeceptors like (this)https://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-Handling401Unauthorized]

**Comment by anagrath** [comment]
Fair enough.  However, that suggestion ignores the original problem which is that the following returns true in the case that I am discussing:

User.isAuthenticated()

So in theory I agree with you, I can work around with the interceptor. Philosophically, however, I do not think this function should return true when the user is not authenticated and it is… when I investigated the code, I found that the get current call is failing due to authentication.

Please advise,

Aditya

**Comment by davidcheung** [comment]
Agreed, we should fix this, perhaps call `LoopBackAuth.clearUser()` upon error somewhere [here](https://github.com/strongloop/loopback-sdk-angular/blob/c8cb9ae945046c6414952c69a8e1fe00480d2c73/lib/services.template.ejs#L152-L169)
