### ISSUE TITLE
fk findbyid include filter

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-sdk-angular#220]
I have a "Customer" and "Order" model. The Customer hasMany Orders

The rest api states that I can get 

    /api/customers/:id/orders/:fk

so /api/customers/1/orders/6 should get me order #6 of customer #1 - and it does!

in angular, I can do

    customer.orders.findById({id: 1, fk: 6}) 

and that also gets me the correct order.

However, order may have a boatload of fields that I may not want, so I want to use the "fields" filter - I may also want to include the "orderlines" relation of the order

How can I pass the filter option in the rest and angular apis ? There seems to be little documentation on it. The backend model findById() method *does* have a filter option 

what am I missing?

**Comment by jonathan-casarrubias** [comment]
Hi @jmls you can not use the include filter on findById.. you will need to update your query to something like:


```javascript
customer.orders({
    id: 1,
    filter: {
        where: { customerId: 6 },
        fields: [],
        include: 'relation'
    }
) 
```

Cheers, Jon

**Comment by davidcheung** [comment]
This issue looks like its resolved? @jmls was wondering if you were able to resolve your issue using the solution above, I'm closing the issue now, please feel free to reopen if its still an issue. Thanks
