### ISSUE TITLE
Nested private relations not generated

### ISSUE THREAD

**Issue by dancingshell** [strongloop/loopback-sdk-angular#222]
Nested relations that are set to `public:false` in the `model-config.json` are available through their parent models in the explorer, but not generated through lb-ng. Lb-ng seems to ignore all models not set to public. 
Currently to access child model in the generated angular the model has to be public. I would like to be able to set models to private so that I can only create them through their parent models, but have these nested functions be available as they are in the explorer.
ie- POST meetups/5/rsvps 

I have model `Meetup` and model `RSVP`

meetup.json
```
"relations": {
    "rsvps": {
      "type": "hasMany",
      "model": "rsvp",
      "foreignKey": "meetupId"
    }
  }
```
rsvp.json
```
"relations": {
  "meetup": {
    "type": "belongsTo",
    "model": "meetup",
    "foreignKey": "meetupId"
  }
}
```

model-config.json
```
  "rsvp": {
    "dataSource": "postgres",
    "public": false
  },
  "meetup": {
    "dataSource": "postgres",
    "public": true
  }
```

**Comment by davidcheung** [comment]
Hi @dancingshell  the functions get populated for me from the angular-sdk side with a similar settings
do you get any errors from the lb-ng generation? my configs are as follows:

**model-config.json**
```json
  "peasant": {
    "dataSource": "db",
    "public": true
  },
  "address": {
    "dataSource": "db",
    "public": false
  }
```
**peasant.json**
```json
  "relations": {
    "addresses": {
      "type": "hasMany",
      "model": "address",
      "foreignKey": "pId",
      "through": "peasant"
    }
  }
```

**lb-services.js**
````js
"prototype$__get__addresses": {
  isArray: true,
  url: urlBase + "/peasants/:id/addresses",
  method: "GET"
},

...

"prototype$__findById__addresses": {
  params: {
  'fk': '@fk'
  },
  url: urlBase + "/peasants/:id/addresses/:fk",
  method: "GET"
},
```

**Comment by davidcheung** [comment]
Hi @dancingshell, not sure if you were able to resolve your issue, I wasn't able to reproduce your issue, closing the issue now, please reopen if you are still experience the issue and would be best if you could provide steps to reproduce or a [sand-box](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report). Thanks
