### ISSUE TITLE
Model.findById ignoring filter

### ISSUE THREAD

**Issue by gianlucamov** [strongloop/loopback-sdk-angular#228]
Hi,
Using the sdk, querying "User" model, the findById seems to ignore any filter ( I would need to use the "include" filter). 
In the documentation is not clear whether this is a supported feature or not.

Is it correct that "findById" is ignoring the filter?

Thank you very much
Gianluca

**Comment by mrbatista** [comment]
@gianlucamov please share your code to help you

**Comment by mrbatista** [comment]
@gianlucamov this is an example:
```javascript
User.findById({id: User.getCurrentId(), filter: {include: 'settings'}}).$promise
    .then(function(user) {
      console.log(user);
    });
```

**Comment by gianlucamov** [comment]
@mrbatista Thank you, here is the code I am using :
`function loggedUser(){
                var id = User.getCurrentId();
                $log.debug("Logged User Id");
                $log.debug(id);
                return User.findById({ id: id },{
                    filter: {
                        include: 'identities'
                    }
                }).$promise;
            }`
I did plainly wrong. Got confused between loopback and angular sdk syntax, examples on official documentation didn't help me but api docs are clear, I will stick to them.
Thank you
