### ISSUE TITLE
uploading files via SDK

### ISSUE THREAD

**Issue by pbrain19** [strongloop/loopback-sdk-angular#232]
There seems to be no documentation on how the uploading of files is happening. Ideally I would like to create a 'customer' that has many images. the api however seems to only like to do these separate.

**Comment by davidcheung** [comment]
Hi @pbrain19 , you could perhaps take a look to see if https://github.com/strongloop/loopback-component-storage/tree/production/example-2.0 helps, please also see https://github.com/strongloop/loopback-sdk-angular/issues/22

I think we need an official way that's easiest for devs to implement a file upload solution, while its not as easy as we would like it to be right now.

**Comment by bajtos** [comment]
Possibly related: #22.

I am afraid we don't have bandwidth to implement this feature ourselves. Contributions are welcome though!
