### ISSUE TITLE
Generate AngularSdk not working using this module

### ISSUE THREAD

**Issue by alvarp** [strongloop/loopback-sdk-angular#236]
This code:

```
var generator = require('loopback-sdk-angular');
var fs = require('fs');
var path = require('path');

module.exports = function (app, callback) {
    if(app.booting) {
        app.on('booted', function () {
            console.log('booted');
            generate(app, callback);
        });
    } else {
        generate(app, callback);
    }
};

function generate(app, callback) {
    var options = {
        output: './client/angular-sdk/lb-services.js', // Other task-specific options go here.
        ngModuleName: 'lbServices'
    };

    options.apiUrl = app.get('restApiRoot') || '/api';
    
    var script = generator.services(app, options.ngModuleName, '/api');

    fs.writeFile(options.output, script, {}, function (err) {
        callback(err);
    });
}
```

Throws the following error:
```
undefined:25
      throw err;
      ^
    
    TypeError: ejs:69
        67|  */
        68|   module.factory(
     >> 69|     <%-: modelName | q %>,
        70|     [
        71|       'LoopBackResource', 'LoopBackAuth', '$injector',
        72|       function(Resource, LoopBackAuth, $injector) {
    
    meta.ctor.getEndpoints is not a function
        at eval (eval at <anonymous> (D:\User\Documents\projects\project\repo\node_modules\loopback-sdk-angular\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:34:314)
        at eval (eval at <anonymous> (D:\User\Documents\projects\project\repo\node_modules\loopback-sdk-angular\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:110:48)
```

**Comment by davidcheung** [comment]
@alvarp what version of loopback are you using? perhaps you are using a new version of `sdk-angular` with an old version `loopback`?

**Comment by alvarp** [comment]
@davidcheung Loopback 2.26.0

**Comment by davidcheung** [comment]
@alvarp looks like the function was added in [strong-remoting@`2.2.7`](https://github.com/strongloop/strong-remoting/commit/9a578165c498555656c73611aa2656ccf19bdeb1) since [loopback-sdk-angular@`1.9.0`](https://github.com/strongloop/loopback-sdk-angular/blob/master/CHANGES.md#2016-07-29-version-190), you should be able to resolve this would be upgrading your strong-remoting to `^2.27.0`+

/cc @bajtos

**Comment by bajtos** [comment]
@davidcheung alternatively, we can modify sdk code-gen to support both API flavours - the new `getEndpoints` and the old `getHttpPath` (IIRC the name correctly).

**Comment by davidcheung** [comment]
@bajtos lets do that
>alternatively, we can modify sdk code-gen to support both API flavours

**Comment by NudgeTech** [comment]
Hi,  I am having a similar issue when using the lb-ng angular services generator command.  I get the same error message.  I have a single model on the sever side.  How do you fix this? Best

**Comment by davidcheung** [comment]
Hi @NudgeTech, the fixed has been checked-in(to master) but we have not release to npm yet. in the mean time you could update to `strong-remoting@2.32.0` in your loopback application that should fix it.

**Comment by NudgeTech** [comment]
@davidcheung Ok thanks, what is the best way to do that?

**Comment by davidcheung** [comment]
@NudgeTech 
i believe you should be able to just do `npm install strong-remoting --save` on your loopback application (if you are using npm3), 

if not you might need to go into `node_modules/loopback/` then do `npm install strong-remoting --save`

i have not tried this myself, please let me know if it works.

**Comment by NudgeTech** [comment]
@davidcheung  What I did was go to the package.json file in loopback folder (node_modules/loopback).  I updated the strong-remote version to 2.23.0 and ran nom install from within the loopback folder.  Then went back to the client folder and ran the lb-ng command. This seemed to work!

**Comment by achrefcharfeddine** [comment]
Thanks, you solved the problem.
