### ISSUE TITLE
Share method source code between angular service and loopback server

### ISSUE THREAD

**Issue by Cadrach** [strongloop/loopback-sdk-angular#24]
Hi,

This really is an open question, I am currently having some business logic that I would like to use client side (for display purpose or "show before saving" purpose), and the same business logic would be used server side on the same loopback model instances; for validation / testing purpose.

What I would love to have, is some method available on my Loopback model instances, and have the same method provided on the object given by the generated angular service.

The aim is to have these functions directly on the object and be able to execute them without any remote call (it is only computing functions) both client & server side.

To be clear, I understand and already used remote methods, but I do not want the client to make a server request for these basics functionnalities.

**Comment by bajtos** [comment]
This is no longer a feature we would like to pursue.
