### ISSUE TITLE
Security hole in js generated file : Enhancement request

### ISSUE THREAD

**Issue by PhilippeCorreges** [strongloop/loopback-sdk-angular#240]
Hello,
First, I have no idea how to flag this as en enhancement request. Sorry about that.

What I saw : When the angular app is bootstraped, it "pings" the server APIs which results in http 200, 403, 401 response.
Even if I have no clue on how this could be solved, it would be nice to avoid such http requests that shows how the APIs are "named"

**Comment by davidcheung** [comment]
@PhilippeCorreges thanks for bringing this up, can you please give more details of what calls were "ping"ed, 
are they the calls that try to authenticate users access token from localStorage?

**Comment by PhilippeCorreges** [comment]
@davidcheung Hi David
Here is what I am talking about (a simple workflow): 
* Create an API (Let's say projects) 
* No relationship, nothing, just make it visible to be accessed.
* Create an angular app and bootstrap it in an index.html with the proper generated lb-services.js file.
* Open Chrome for instance and look at the network tab of developper tools.
* Start the server and access the app.

In the network tab, you will see that the http://localhost:3000/api/projects is accessed!

Depending on security you set, it can be a http 200 or 401 unauthorized response.

I think the api must not be accessed as the client must see end points (even if not accessible) once requested by the app, only.

Philippe

**Comment by davidcheung** [comment]
@PhilippeCorreges  i dont seem to have that issue
would it be some extensions u have on chrome,
or can you fork a sandbox to reproduce the problem? https://github.com/strongloop/loopback/wiki/Reporting-

![screen shot 2016-09-22 at 12 27 13 pm](https://cloud.githubusercontent.com/assets/1787590/18757025/1966df68-80c0-11e6-8686-d2a8bac62802.png)

**Comment by PhilippeCorreges** [comment]
Hi !!
The problem with a plugin was a good idea to me and I tested on Safari too (In fact I did it already) 
So, here is a screenshot from Safari : 

![capture d ecran 2016-09-26 a 15 34 18](https://cloud.githubusercontent.com/assets/11230777/18836115/d9079380-83fe-11e6-8869-7f3db8dc6944.png)

You can also use a repo like https://github.com/beeman/loopback-angular-admin

You will see that the app is, according to the source code, redirected to the login page as there is a "ping" to the APIs.

PS : I am a newbee and still have no clue how to fork a sandbox. I will look into this today or tomorrow to help you if needed.

Philippe

**Comment by davidcheung** [comment]
I think those are the requiring of the js files, can you see if those are ajax calls? or simply just the app requiring the `.js` scripts to boot the app, if you want to hide the **controllers js files**, you could use a task runner such as `gulp` to `minify` your application then it would hide the model names.

**Comment by bajtos** [comment]
I am closing this issue because it's not clear how to reproduce it.
