### ISSUE TITLE
Api docs not showing all functions

### ISSUE THREAD

**Issue by aks0020** [strongloop/loopback-sdk-angular#242]
Below api doc link is not showing all function details:
http://apidocs.strongloop.com/loopback-sdk-angular/

**Comment by davidcheung** [comment]
@aks0020 thanks for bringing this up, somehow the https://github.com/strongloop/loopback-sdk-angular/blob/b22c92342942cf3c31c9f194c7496d64afb03269/package.json#L8 did not get properly generated for the docs

**Comment by davidcheung** [comment]
Thanks @aks0020 the problem should be fixed now
