### ISSUE TITLE
configurable timeouts for services

### ISSUE THREAD

**Issue by davidcheung** [strongloop/loopback-sdk-angular#249]
moved here from https://github.com/strongloop/loopback-sdk-angular-cli/issues/42

Find a way to make timeout configurable for resouces

@hussainak can u see if this describes your issue/feature request?

**Comment by hussainak** [comment]
yes looks good

**Comment by pbouda** [comment]
I would also like to see this feature in order to be able to cancel resource requests as described here: http://stackoverflow.com/questions/29402697/cancel-a-resource-request-in-angular

**Comment by hussainak** [comment]
It has been 7 months in the making, I guess this will be pushed out soon.

**Comment by bluemixgarage** [comment]
Is this feature available now?

**Comment by bajtos** [comment]
I am afraid we don't have bandwidth to implement this feature ourselves. Contributions are welcome though!
