### ISSUE TITLE
Support multiple lbServices pointing to different servers

### ISSUE THREAD

**Issue by Traksewt** [strongloop/loopback-sdk-angular#250]
Currently the generator can make unique model names for the whole module, but there are other included angular objects that clash with the global angular namespace.

This causes a problem when trying to use 2 lbServices, each pointing to a different server. 

e.g. in config when setting up the URL:
`LoopBackResourceProvider.setUrlBase(myURLBaseForFirstServer);
`
there is no way to setup the base URL for myURLBaseForSecondServer

LoopBackResource, LoopBackAuthRequestInterceptor, LoopBackAuth need to have an optional suffix to allow different base URLs.
e.g.
LoopBackResourceFirstServerProvider.setUrlBase(myURLBaseForFirstServer);
LoopBackResourceSecondServerProvider.setUrlBase(myURLBaseForSecondServer);

I'm happy to put together a patch for this.

**Comment by jdschreck** [comment]
What is that status of this capability?  Has it been released yet?  I am running into this issue also.

**Comment by bajtos** [comment]
@jdschreck See https://github.com/strongloop/loopback-sdk-angular/pull/251 which was never finished. Would you like to pick up the work and finish the pull request to a state where it can be landed?

**Comment by Traksewt** [comment]
@bajtos @jdschreck sorry for delay, I will finish unit tests and push up today.

**Comment by bajtos** [comment]
I believe this has been addressed by #269.
