### ISSUE TITLE
upsert does not update relationship properties

### ISSUE THREAD

**Issue by dleute** [strongloop/loopback-sdk-angular#252]
Let's say I have a simple MyModel instance:

```
{
id: uniqueid
name: "My name",
statusId: 2
}
```

statusId is a belongsTo on this model connected to another model called status.

On the first upsert called when id doesn't exist or is 0, the statusId is set after upsert is called like this:

```
MyModel.upsert(model).$promise.then(function () {
// code here to close pop-up panel and refresh data
          });
```

On subsequent calls (when someone edits the same object later and uniqueid has a value) changes to statusId are not saved back to the database. Effectively all drop downs that are relationships on this model can never be changed.

Is this expected behavior? It seems like upsert should update all of a model's properties including relationships.

If so, how do I update an existing model from angular?

--Derrek

**Comment by dleute** [comment]
FYI, I was able to bind my md-select and md-options to the model using the status property instead of the statusId. I worked around it.

I don't understand why using statusId is ok on create but ignored on update. Is this intentional?

**Comment by bajtos** [comment]
@kjdelisle assigning to your team, see my comment in #262

**Comment by bajtos** [comment]
@dleute sorry for the long silence. Is this issue still relevant? Could you please create a small application based on our sandbox repo (see https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report) that we can use to reproduce the problem?
