### ISSUE TITLE
Relative path for Storage FileSystem

### ISSUE THREAD

**Issue by Ktl-XV** [strongloop/loopback-sdk-angular#255]
When generating the SDK, either with grunt or CLI, the build fails when:

- Using `loopback-component-storage`
- Using `"provider": "filesystem"`
- Using a relative path as the `root`
- Building from a directory other than the project root

This makes using the grunt plugin or `lb-ng` from within the client directory impossible. Could there be a way to pass the project root directory, or for it to auto detect it?

I think this has to do with strongloop/grunt-loopback-sdk-angular#27

**Comment by bosco-li** [comment]
@Ktl-XV sorry for the late reply on this.  We put this in our backlog will prioritize for this item.  Thanks so much for the issue.

**Comment by totalard** [comment]
Dear,

The Problem is happen Only when using Relative Path. May be this is useful for temporary fix

**Comment by bajtos** [comment]
I am afraid we don't have bandwidth to implement this feature ourselves. Contributions are welcome though!
