### ISSUE TITLE
lb-ng doesnt work as expected

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback-sdk-angular#261]
this time i got nodejs 7.1.0, loopback 3.1.0, the lastest angular sdk, and latest installed strongloop.

i fired it up with
lb-ng server.js client/js/services/lbservices.js

i got the file generated but all the models defined in my configurations were all gone. i cannot tell how to fix it.

**Comment by jjhesk** [comment]
i just read the similar issues from #221 and there are some issues that happens the same me in here. In the model json there is empty in acl and i never thought of adding anything to it be because there are no carveat pointed out in the documentation of loopback 3.0. please point out the instruction for making the generator to work again. thankx

**Comment by bajtos** [comment]
Hello, is this issue still relevant? Considering that Node.js 7.x will go out of support soon, can you reproduce the problem on Node.js 8.0 too?

**Comment by bajtos** [comment]
Closing this issue as abandoned. Feel free to reopen if you can provide us with the information asked for.
