### ISSUE TITLE
Generated files are too large, option to compress/shrink sdk?

### ISSUE THREAD

**Issue by Undrium** [strongloop/loopback-sdk-angular#263]
Currently there doesn't seem to be any option to make the generated file smaller when generated. Would be really nice to see something which ignores comments/optimizes the size instead of running a third party tool. 

This is a great synergy to https://github.com/strongloop/loopback/issues/989 I believe.

**Comment by bajtos** [comment]
Hello, minification of the generated output is out of scope of this project. Our focus is on providing the best client generator for AngularJS (1.x). Feel free to use the API provided by loopback-sdk-angular (and consumed by our CLI, Gulp and Grunt flavours) to build a new tool that can produce a minified client code.
