### ISSUE TITLE
lb-sdk ignores --wipe

### ISSUE THREAD

**Issue by JuergenSimon** [strongloop/loopback-sdk-angular#279]
# Description/Steps to reproduce

When I run the following command:

`./node_modules/.bin/lb-sdk ./server/server.js ./bellyaches-mobile/app/shared/sdk -d ng2native -i disabled --wipe
`

the process hangs waiting for a response on the question: 

> WARNING: The targeted SDK Directory is not empty, do you want to erase its content? (Y/n) 

Only when combining it with --quiet is the result as expected.

**Comment by bajtos** [comment]
Hello, I am afraid you submitted the issue to a wrong project - loopback-sdk-angular-cli provides `lb-ng` command, not `lb-sdk`. 

I think https://github.com/mean-expert-official/loopback-sdk-builder may be the GitHub repository you are looking for?
