### ISSUE TITLE
Relationships defined in Mixins don't generate Angular Services

### ISSUE THREAD

**Issue by luncht1me** [strongloop/loopback-sdk-angular#283]
I have a little mixin that simply creates relationships between one model and the other (plus some supporting logic)

```js
var relationDefinition = {
	as: 'images',
	polymorphic: "imageable"
};

// Define relationship
Model.hasMany(Image, relationDefinition);
```

My API, explorer, server-side dot notations, client-side includes all work perfectly well. The relation is built as intended. It's just, my `lb-services.js` file doesn't have an interface to work with. So, say I had a model called `Sponsor` which `hasMany` `Image`, there's no `Sponsor.image({ id: sponsor.id})` service available to me in Angular.

**Comment by bajtos** [comment]
This looks like a missing feature to me! Would you like to contribute the implementation yourself, @luncht1me? I am happy to help you along the way.

**Comment by bajtos** [comment]
With the release of LoopBack 4.0 GA (see the [announcement](https://strongloop.com/strongblog/loopback-4-ga)), this SDK has entered Active LTS mode which means we are no longer accepting new features (see our [LTS policy](https://loopback.io/doc/en/contrib/Long-term-support.html)).

I am closing this issue as "won't fix".
