### ISSUE TITLE
Can you publish this to NPM? it' still at version 3.3.0

### ISSUE THREAD

**Issue by sebolio** [strongloop/loopback-sdk-angular#294]
Hello, I need to use this tool and I can't because it's outdated on NPM repository. I hope you could fix this soon please.

**Comment by dhmlau** [comment]
Saw that @bajtos has published earlier today and the latest version is 3.4.1.  Is it what you're looking for?

**Comment by dhmlau** [comment]
@sebolio , I'd like to close this issue as the latest version is 3.4.1.  Thanks.
