### ISSUE TITLE
Implement "Add" method for hasAndBelongsToMany and hasMany through

### ISSUE THREAD

**Issue by Cadrach** [strongloop/loopback-sdk-angular#30]
Hi,

Unless I am mistaken, there is currently no method exposed on the generated services to "link" 2 existing model instances. For example provided model Product and Category with:

``` js
Product.hasAndBelongsToMany ('categories', {model: Category, foreignKey: 'categoryId'});
```

I can only create a model using the service, but I cannot link a product to an existing category (and the reverse too)

**Comment by adanielyan** [comment]
Can you please provide an example of using the link function? I am struggling with it trying to add a new relationship between two modules in angular. How should the function parameter object be constructed? I tried 
```
RegionalData.sectors
            .link({id: regionalData.id, fk: sector.id})
```

as well as tried to replace fk with sectorId or even provide two different objects like
```
link({id: regionalData.id}, {fk: sector.id})
```

but neither worked.

**Comment by jonathan-casarrubias** [comment]
That has been already discussed in https://github.com/strongloop/loopback-sdk-angular/issues/78 

cheers
jon

**Comment by adanielyan** [comment]
Thank you jon. I found that solution but forgot to update the thread here.
