### ISSUE TITLE
Auto Logout after a specific interval of time.

### ISSUE THREAD

**Issue by Surender246** [strongloop/loopback-sdk-angular#39]
Hi i have a Login page for my application by which user access rest of the pages by logging in but i want that user to logout automatically if there is no action from the user for a specific interval of time.how to achieve this in angular. thanks in advance.

**Comment by NabinKhatiwada** [comment]
1.create a service class-service class is at the end and add following code. 
        2.create a component and provide there and inject there example:
      import { Component, OnInit } from '@angular/core';
        import { AutoLogoutService } from './auto-logout.service';
        @Component({
          selector: 'app-auto-logout',
          templateUrl: './auto-logout.component.html',
          providers: [AutoLogoutService]
        })
        
        export class AutoLogoutComponent implements OnInit {
        
          constructor(private autoLogoutService: AutoLogoutService) { }
        
          ngOnInit() {
          }
        
        }
        3. add this component to app_module and use the tag in common page like 
        full-layout-component.html. tag eg: <app-auto-logout></app-auto-logout>
    
    
        4. you should initialize the localStorageValue once your full layout component or common page loads.
        
    
     
    export class FullLayoutComponent implements OnInit {
     constructor(){
    localStorage.setItem('lastAction',Date.now().toString());
      }
    }
    }
    
        
        import { Injectable } from "@angular/core";
        import { Router } from '@angular/router'
        // import {} from ''
        // const store = require('store');
        
        const MINUTES_UNITL_AUTO_LOGOUT = 60 // in mins
        const CHECK_INTERVAL = 15000 // in ms
        const STORE_KEY =  'lastAction';
        @Injectable()
        export class AutoLogoutService {
         public getLastAction() {
            return parseInt(localStorage.getItem(STORE_KEY));
          }
         public setLastAction(lastAction: number) {
            localStorage.setItem(STORE_KEY, lastAction.toString());
          }
        
          constructor(private router: Router) {
            console.log('object created');
            // this.auth = authService;
            this.check();
            this.initListener();
            this.initInterval();
            // localStorage.setItem(STORE_KEY,Date.now().toString());
          }
        
          initListener() {
            document.body.addEventListener('click', () => this.reset());
            document.body.addEventListener('mouseover',()=> this.reset());
            document.body.addEventListener('mouseout',() => this.reset());
            document.body.addEventListener('keydown',() => this.reset());
            document.body.addEventListener('keyup',() => this.reset());
            document.body.addEventListener('keypress',() => this.reset());
          }
        
          reset() {
            this.setLastAction(Date.now());
          }
        
          initInterval() {
            setInterval(() => {
              this.check();
            }, CHECK_INTERVAL);
          }
        
          check() {
            const now = Date.now();
            const timeleft = this.getLastAction() + MINUTES_UNITL_AUTO_LOGOUT * 60 * 1000;
            const diff = timeleft - now;
            const isTimeout = diff < 0;
        
            // if (isTimeout && this.auth.loggedIn)
            if (isTimeout)  {
              // alert('logout');
              localStorage.clear();
              this.router.navigate(['./login']);
            }
          }
        }

**Comment by NabinKhatiwada** [comment]
Hmm..this should work also..since this service is not required for other components,I added in the component itself. And that component I placed where ever required. Thank you :)

**Comment by bajtos** [comment]
Looks like this feature does not require any changes in our SDK - I am closing the issue as resolved.

**Comment by satish1020** [comment]
Can you please explain the fourth point and how is auto-logout.component.html page is there a git hub repository where I can view this code.

**Comment by NabinKhatiwada** [comment]
4th point. There is no data in html,just use it as tag where (means - other components html section)you require auto logout.<app-auto-logout></app-auto-logout>

**Comment by satish1020** [comment]
So i need to use <app-auto-logout></app-auto-logout> in all my html pages. and auto-logout.component.html  is just an empty html?

**Comment by NabinKhatiwada** [comment]
Yes correct.
Extra tip:  If you already have a layout section that is common to all the web-pages in your project,you just have to include tag there and you can provide the service in app.module.ts.

**Comment by satish1020** [comment]
Thanks a lot for your prompt response.Its not logging me out for some reason is there a gihub link with a sample?

**Comment by NabinKhatiwada** [comment]
I am sorry. I don't have time to create a sample project. But if you follow steps correctly, It should definitely work. Try to debug and check in your localStorage as you hover you mouse over your page,see if local storage is getting updated. 
![capture](https://user-images.githubusercontent.com/26105836/39345601-06d895dc-4a07-11e8-9dc1-74720a820eaf.PNG)

**Comment by satish1020** [comment]
I had   localStorage.setItem('lastAction',Date.now().toString()); in the constructor of my app.component.ts and i have it in <app-auto-logout></app-auto-logout> in  app.component.html as well as index.html but it is not working

**Comment by satish1020** [comment]
I have one more question it would be great help if you can reply. The Current functionality will log me out after a period of inactivity.What if I have to Logout irrespective of Inactivity.

**Comment by satish1020** [comment]
Yes it worked basically  setting up  localStorage.setItem('lastAction', Date.now().toString()); on login success and we don't need initListener and reset functions in Auto Logout Service will let the application logout after a specific time.

**Comment by amalaxavier** [comment]
Thanks for your help. It works:)

**Comment by oessniravpatel** [comment]
hiii Can you please help me 
I am opening tab 1, finish our work and leave it open, then open tab two and continue working in tab two for 15 minutes, tab one will return to the log in page due to automatically logout(Timeout set in 15 minutes in).

**Comment by duyhoangptit** [comment]
> 1. create a auto logout service using following command at root folder
>    -> ng generate service services/auto-logout
>    include this service to app_module
> 2. create a component using below command and provide there and inject there example:
>    -> ng generate component components/auto-logout
>    import { Component, OnInit } from '@angular/core';
>    import { AutoLogoutService } from './auto-logout.service';
>    @component({
>    selector: 'app-auto-logout',
>    templateUrl: './auto-logout.component.html',
>    providers: [AutoLogoutService]
>    })
>    export class AutoLogoutComponent implements OnInit {
>    ```
>     constructor(private autoLogoutService: AutoLogoutService) { }
>    
>     ngOnInit() {
>       localStorage.setItem('lastAction', Date.now().toString());
>     }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    }
> 
> include this component to app_module
> 
> 3. Add following codes in the your auto-logout service file created in 1) step
>    ```
>    import { Injectable } from '@angular/core';
>    import { Router } from '@angular/router'
>    
>    const MINUTES_UNITL_AUTO_LOGOUT = 10 // in mins
>    const CHECK_INTERVAL = 15000 // in ms
>    const STORE_KEY = 'lastAction';
>    @Injectable()
>    export class AutoLogoutService {
>    
>      public getLastAction() {
>        return parseInt(localStorage.getItem(STORE_KEY));
>      }
>      public setLastAction(lastAction: number) {
>        localStorage.setItem(STORE_KEY, lastAction.toString());
>      }
>    
>      constructor(private router: Router) {
>        console.log('object created');
>        this.check();
>        this.initListener();
>        this.initInterval();
>      }
>    
>      initListener() {
>        document.body.addEventListener('click', () => this.reset());
>        document.body.addEventListener('mouseover', () => this.reset());
>        document.body.addEventListener('mouseout', () => this.reset());
>        document.body.addEventListener('keydown', () => this.reset());
>        document.body.addEventListener('keyup', () => this.reset());
>        document.body.addEventListener('keypress', () => this.reset());
>      }
>    
>      reset() {
>        this.setLastAction(Date.now());
>      }
>    
>      initInterval() {
>        setInterval(() => {
>          this.check();
>        }, CHECK_INTERVAL);
>      }
>    
>      check() {
>        const now = Date.now();
>        const timeleft = this.getLastAction() + MINUTES_UNITL_AUTO_LOGOUT * 60 * 1000;
>        const diff = timeleft - now;
>        const isTimeout = diff < 0;
>    
>        if (isTimeout) {
>          localStorage.clear();
>          this.router.navigate(['/']);
>        }
>      }
>    }
>    ```
> 
> 4 ) Add '' tag at the top or bottom of every .html file of component or .template section of ts file in components.
> 
> NOTE: you need to use '''' only in those components, which are calling using routing url. i.e. no need to add into child components.
> 
> I hope, it will help you to achieve auto logout feature in angular 2 and above.

I find that your solution will make down web performance because Browser always write value into local storage. If your screen has a lot of field input on screen, you will feeling very slow when you typing to input.
