### ISSUE TITLE
User password is set to NULL after any User profile updates

### ISSUE THREAD

**Issue by BradleyFord** [strongloop/loopback-sdk-angular#44]
Currently we are experiencing some problems with the Angular SDK.

We are using the User model (with some additional fields); any time we update any details about the user such as First name, Last name, Position, etc the password is set to NULL. (MongoDB)

```
   $scope.updateProfile = function() {
        $scope.updateProfile.status = '';
        User.upsert($scope.profile, function() {
            $scope.updateProfile.status = 'success';
        }, function() {
            $scope.updateProfile.status = 'fail';
        });
    };
```

updateOrCreate was also tried with the same results

```
   $scope.updateProfile = function() {
        $scope.updateProfile.status = '';
        User.updateOrCreate($scope.profile, function() {
            $scope.updateProfile.status = 'success';
        }, function() {
            $scope.updateProfile.status = 'fail';
        });
    };
```

But if we switch the User.upsert to a HTTP.put request we do not experience this error.

```
    $scope.updateProfile = function() {
        $scope.updateProfile.status = '';
        $http.put(conf.apiRoot + 'users/' + Profile.id, $scope.profile).success(function() {
            $scope.updateProfile.status = 'success';
        }).error(function() {
            $scope.updateProfile.status = 'fail';
        });
    };
```

I am not sure if this is related to the recent bug fixes in datasource-juggler (https://github.com/strongloop/loopback-datasource-juggler/pull/108), but we have updated and retested since that patch with the same results.

**Comment by mariohmol** [comment]
I had a similar problem and it was related to password with a small size.. it has a validation somewhere but do not rise a error.. it just put null in place of it

**Comment by geekguy** [comment]
I second @mariohmol.  started facing this issue in latest version.
