### ISSUE TITLE
set urlBase with another javascript file

### ISSUE THREAD

**Issue by paulomcnally** [strongloop/loopback-sdk-angular#60]
How to set urlBase with other var?

api.js is generated based on environment (http://client.site.com/js/api.js)
api.js

```
var apiUrlBase = 'https://production.site.com/api'; // or http://develop.site.com/api or http://localhost:3000/api
```

lb-services.js is generated vía loopback-sdk-angular (http://client.site.com/js/lb-services.js)
lb-services.js

```
(function(window, angular, undefined) {'use strict';
    var urlBase = "/api"; // ???
...
```

**Comment by SinvalMAO** [comment]
Thank @arielschiavoni, I'm using ionic to develop an application, and reused the "loopback-angular-sdk", however as the angular injects URLBase of dynamic way according to what is caught in the browser, it always gave 404 NOT FOUND as Substitutes by a static it worked perfectly =)
