### ISSUE TITLE
Support for loopback-component-passport

### ISSUE THREAD

**Issue by frankcarey** [strongloop/loopback-sdk-angular#74]
Trying to use the additional methods for 3rd party login. The generator doesn't seem to pick up on those endpoints/callbacks? (nor does loopback explorer for that matter)

What would be the best way to add / alter login to handle this?

**Comment by bajtos** [comment]
There are no updates so far, we still need to implement support for cookie-based authentication in loopback-sdk-angular, including support for signed cookies.

**Comment by clarkorz** [comment]
Is there any plan to support [loopback-component-oauth](https://github.com/strongloop/loopback-component-oauth2)?

**Comment by esco** [comment]
:+1:

**Comment by PeterClough** [comment]
"implement support for cookie-based authentication in loopback-sdk-angular"

Any ideas on timescales for this work to be implemented please?

**Comment by thovden** [comment]
I had this same issue, and have solved it by patching loopback-component-passport to support including the accessToken in the `successRedirect` URL. I have a gut feeling this is dubious from a security point of view, and if so, I hope you will tell me why. 

The setup is as follows. I have an AngularJS app running on one domain, and the Loopback server on another. Both run TLS-only in production. 

The changes to `passport-configurator.js`: https://gist.github.com/thovden/b4d67942fc23880a7957 

The JSON config will look something like this:
```json
{
"facebook-login": {
  "provider": "facebook",
  "module": "passport-facebook",
  "clientID": "...",
  "clientSecret": "...",
  "callbackURL": "http://localhost:3000/auth/facebook/callback",
  "authPath": "/auth/facebook",
  "callbackPath": "/auth/facebook/callback",
  "successRedirect": "https://mysite.com/#/extLogin/:accessToken/tab.consents", 
  "scope": ["email"]
}
```
The extLogin AngularJS controller will simply login the user using the provided accessToken, using another trick. The problem is getting the User into localStorage. Until then, `User.getCurrent()` etc. will fail. However, the loopback server will accept requests with a valid accessToken, so I've made remote method `User.current()` that simply returns the User object for a valid accessToken. 

```javascript
  $scope.accessToken = $stateParams.accessToken;
  $scope.nextState = $stateParams.nextState;

  LoopBackAuth.accessTokenId = $scope.accessToken;
  LoopBackAuth.rememberMe = true;
  LoopBackAuth.save();

  // Now get the user from the server. Since we've set the access token,
  // the server will identify the user safely.
  User.current(function(user) {
    console.log("User.current returned ", user);

    // Update the localStorage with current data
    $scope.currentUser = user;
    LoopBackAuth.setUser($scope.accessToken, user.id, user);
    LoopBackAuth.save();

    $state.go($scope.nextState);

  }, function(err) {
    console.log("ERROR: User.current returned ", err);
    $state.go('login', {nextState: $scope.nextState});
  });
```
Finally, the implementation of `User.current()`
```javascript
    User.current = function(cb) {
      var ctx = loopback.getCurrentContext();
      var accessToken = ctx.get('accessToken');
      if (! accessToken) {
        cb('Invalid or missing accessToken');
        return;
      }
      User.findById(accessToken.userId, function(err, user) {
        err ? cb(err) : cb(null, user);
      });
    }

    User.remoteMethod('current', {
      returns: {arg: 'user', type: 'object', root: true},
      http: {path:'/current', verb: 'get'}
    });
```

**Comment by ahmed-abdulmoniem** [comment]
@frankcarey
Can I know how to tell loopback-passport to send params to the url instead of session/cookie? I mean should I add some configuration to the `providers.json` for example or what exactly?

Also, I have strongloop in the backend .. but the consumer is an ionic app/cordova which should be installed to the mobiles so how can I redirect to it?

**Comment by mialso** [comment]
i think there is a way to solve this by adding new option in `providers.json`
 ```
"google-login": {
...
"populateSessionStorage": true
}
```
and then `passport-configurator.js` add handler (line 403)
```
 else if(!!populateSessionStorage) {
        return res.send(getScriptToSend((user.id, info.accessToken.id, successRedirect));
}
```
function getScriptToSend():
```
function getScriptToSend(userId, accessTokenId, redirect) {
  var script = ' ';
  script += '<script type="text/javascript">';
  script += 'sessionStorage.setItem("$LoopBack$accessTokenId", "';
  script +=  accessTokenId;
  script += '");';
  script += 'sessionStorage.setItem("$LoopBack$currentUserId", "';
  script += userId;
  script += '");';
  script += 'window.location = "';
  script += redirect;
  script += '";'
  script += '</script>'
  return script;
```
this workaround adds data(tokenId & userID) to browser sessionStorage before angular-client loading, so we are able to call User.getCurrent() and all other stuff.
Are there any critical issues in this approach?

**Comment by nick-anykeydesigns** [comment]
Any update on an official solution?

**Comment by prabhdeep-singh** [comment]
@frankcarey 
Hi Frank, I tried your solution to get the redirected url with access_token attached as params to it but it gives me this error:

`404 Error: Cannot GET /login/callback?access_token=xxxxxxxxxxxxxxxxxx&userId=1`

It successfully authenticates from the facebook and gives the token but somehow it does not pick the redirected URL.

I'm using ui-router and have state setup for url "/login/callback" but it does not seem to pick it up. 

Also, the code you provided for customCallback option in PR [23](https://github.com/strongloop/loopback-component-passport/pull/23) Whenever I pass that in the `passportConfigurator.configureProvider(strategy, opts);`

I get reference error as "Passport cannot be referenced".

What am I doing wrong here? Please help.

**Comment by mehlleniumfalke** [comment]
I got the same problem here. Trying to establish a loopback-passport-angular app for simple time logging. Here is whats happening:

1. Login via Button
2. Button redirects to google and auths
3. redirect back to my app

Now i got userId and accessToken in my local storage. But they are not plain.
So how do is got the userId in Plain to work with and tell my app that the currentUser is logged in?
Thankful for any help.
greetz

**Comment by gvillenave** [comment]
Any updates here?

**Comment by bajtos** [comment]
No updates, I am afraid this feature is (still) not a priority for us. Are there any volunteers to contribute the implementation?

**Comment by jashanbhullar** [comment]
Any updates on this? Any solid workarounds?

**Comment by bajtos** [comment]
I am afraid we don't have bandwidth to implement this feature ourselves. Contributions are welcome though!
