### ISSUE TITLE
link method not attaching fk to url, failing to create relationship

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-sdk-angular#78]
using loopback-sdk-angular 1.2.2
loopback: 1.10.0

VendorOrder hasAndBelongsToMany Part and vice versa.

Trying to build a relationship between two existing models. 

```
return VendorOrder.part.link({ id: 'abc', fk: '123' }).$promise;
```

Request URL generated: http://localhost:9000/api/vendorOrders/abc/part/rel

Request payload: { id: 'abc', fk: '123' }.

Adding a relationship from loopback-explorer works fine. Seems that $resource is not attaching fk to the url.

**Comment by ahmed-abdulmoniem** [comment]
This is not working.

Tried to pass null, empty, duplicate objects and always I receive 404.

Any solution please?

or should I call the api myself using $http?

**Comment by ahmed-abdulmoniem** [comment]
Still I am trying to do the workaround of passing null, empty, duplicate object to the link method but it is not working.

Here is my code:

`.MallBranch.customPromotions.link({
              id: item.id,
              fk: promotionAfterCreation.id
            }, null);`

or even

`.MallBranch.customPromotions.link({
              id: item.id,
              fk: promotionAfterCreation.id
            }, {
              id: item.id,
              fk: promotionAfterCreation.id
            });`

or even more

`.MallBranch.customPromotions.link({
              id: item.id,
              fk: promotionAfterCreation.id
            },{
              mallBranchId: item.id,
              customPromotionId: promotionAfterCreation.id
            });`

Always gives me an error in the browser console:

`PUT http://localhost:3000/api/MallBranches/55027ad139cb44c8431e4e83/customPromotions/rel 404 (Not Found)`

any solutions please?

**Comment by jonathan-casarrubias** [comment]
The result error says that there is not "http://localhost:3000/api/MallBranches/55027ad139cb44c8431e4e83/customPromotions/rel" path, so in my understanding you are not passing the FK, even I see you actually try to pass it, no body can assure that promotionAfterCreation.id has a value.

My assumption is that promotionAfterCreation.id is in fact empty, because your route should be something like "http://localhost:3000/api/MallBranches/55027ad139cb44c8431e4e83/customPromotions/rel/xxxxxxxxx" 

where obviously xxxxxxxxx should be the id from the related model.

Cheers.
Jon

**Comment by ahmed-abdulmoniem** [comment]
In fact no. I am passing the Id and it is not empty.

My solution (workaround) is to hook on beforeRemote and afterRemote events of the create method of my model and do the work there in the server and it worked with the same data I was trying to pass to the REST service.

Still, I can't solve the REST issue!

**Comment by jonathan-casarrubias** [comment]
Well, that is really strange the only thing i know is that the final url is not being created correctly.. not sure why then if you say you are sure there is a value id right before the call..  you could try building your own $resource or simply use $http and build the url by your own... 

Cheers
jon

**Comment by bajtos** [comment]
Could you please create a sample app reproducing the issue per https://github.com/strongloop/loopback/wiki/Reporting-issues?

**Comment by mattmccabe** [comment]
I just ran into this issue as well and I believe it's happening due to how the angular resources are generated by lb-ng tool. 

In my example, my code is:
```
Workflow.roles.link({id:CurrentWorkflow.id, fk:roleId});
```
Which ends up at the below action defined in the 'WorkRole' resource (lb-ng generated lb-services.js excerpt) :
```
        // INTERNAL. Use Workflow.roles.link() instead.
        "::link::Workflow::roles": {
          url: urlBase + "/Workflows/:id/roles/rel/:fk",
          method: "PUT"
        },
```
The  'action' defined here isn't specifying 'fk' as a param. The 'id' is getting projected into the url because of the paramDefaults that are specified on the resource as you can see from this excerpt:
```
module.factory(
  "WorkRole",
  ['LoopBackResource', 'LoopBackAuth', '$injector', function(Resource, LoopBackAuth, $injector) {
    var R = Resource(
      urlBase + "/WorkRoles/:id",
      { 'id': '@id' } /* <== These are the paramDefaults, used for every action defined in the resource*/,
      {
```
You can resolve the missing 'fk' value from the url by adding an 'fk' to the params field of the resource action, the action will extract the fk value from the object passed to Workflow.roles.link(),  like this:
```
        // INTERNAL. Use Workflow.roles.link() instead.
        "::link::Workflow::roles": {
          url: urlBase + "/Workflows/:id/roles/rel/:fk",
          method: "PUT",
          params: {'fk':'@fk'} 
        },
```
Docs on angular resource that helped me out: https://docs.angularjs.org/api/ngResource/service/$resource

My caveat is that I cringe a little editing the generated code because I will have to make the change several times until I can get in an look at the source for lb-ng.

...and the beat goes on
-Matt

**Comment by bajtos** [comment]
Thanks @mattmccabe for detailed analysis. To me, this looks like a general shortcoming of the current implementation where we don't correctly detect method arguments that are mapped to path params. 

To fix it, we need to modify `lib/services.js` to process arguments and detect those with `http.source === 'path'`. Then we need to change `lib/services.template.ejs` to use this new information to include a correct `params` option in each method emitted.

**Comment by ahmed-abdulmoniem** [comment]
Thank you all.

This would be available on which version .. I mean should I update my bower.json version to what?

**Comment by ahmed-abdulmoniem** [comment]
@bajtos Can you please point out the place which I can change in `lib/services.js` to process arguments and detect those with `http.source === 'path'`

Also the place which I need to change in `lib/services.template.ejs` to use this new information to include a correct `params` option in each method emitted?

I need this fix urgently .. Thanks.

**Comment by bajtos** [comment]
>  Can you please point out the place which I can change in `lib/services.js` to process arguments and detect those with `http.source === 'path'`

See https://github.com/strongloop/loopback-sdk-angular/blob/fa7668b8e11e04fad8d239558846804e5d6315f8/lib/services.js#L57-L65, we are already doing a bit of argument processing there.

> Also the place which I need to change in lib/services.template.ejs to use this new information to include a correct params option in each method emitted?

https://github.com/strongloop/loopback-sdk-angular/blob/fa7668b8e11e04fad8d239558846804e5d6315f8/lib/services.template.ejs#L86-L88

Don't forget to add a unit-test verifying your implementation. We already have some tests for hasAndBelongsToMany relation, just add a new test to check the method `link`.

https://github.com/strongloop/loopback-sdk-angular/blob/fa7668b8e11e04fad8d239558846804e5d6315f8/test.e2e/spec/services.spec.js#L580-L701

Good luck and let me know if you need any more help. You can ping me on [gitter](http://gitter.im/strongloop/loopback) too, just keep in mind that I live in the timezone CEST/UTC+2.

**Comment by erikverheij** [comment]
I still have to add null to get it working;

```javascript
return Order.product.link({ id: 'abc', fk: '123' }, null);
// --> Request payload: empty (as expected)
```

When null is omitted, data is added to the payload.
```javascript
return Order.product.link({ id: 'abc', fk: '123' });
// --> Request payload: {id: 'abc', fk: '123'}
```


In some cases this results in an error in the back-end.

**Comment by bajtos** [comment]
@erikverheij I think that's a generic problem of ngResource. All POST actions take four arguments (params, data, successCb, errorCb), with the first parameter being optional. In other words, if you provide only one object argument, then it's treated as POST data by the framework. I think this is another argument why we should drop ngResource and generate isomorphic-like API instead - see #133

**Comment by erikverheij** [comment]
@bajtos isn't it possible to let the .link()  method set the optional argument to {}  by default?

**Comment by bajtos** [comment]
@erikverheij I am not aware of any solution. You can take a look at ngResource implementation yourself, it's possible that I just did not spot the way: https://github.com/angular/angular.js/blob/dc0b856e9c540fc8453d83f1be12bdfa1662b013/src/ngResource/resource.js#L520-L554

**Comment by erikverheij** [comment]
@bajtos, thanks for your reply. I'm quite busy right now, but I'll try to figure out a a solution in a few weeks.

**Comment by csvan** [comment]
@bajtos the workaround with passing `null` works in my case, but is this really intended behavior as far as RESTful APIs are concerned? Should not `link` only associate one model with another, and in that case do we really need the third parameter?

**Comment by csvan** [comment]
@bajtos - would it not be possible to generate a wrapper function for the `link` methods, which simply nulls the third parameter before passing it on to Resource?

**Comment by bajtos** [comment]
> @csvan would it not be possible to generate a wrapper function for the link methods, which simply nulls the third parameter before passing it on to Resource?

It is possible, although I don't like that. Let me explain why: at the moment, lb-services have the same API as ngResource. You are proposing to subtly deviate from that API and provide custom function signatures for certain model methods. I think that would create even more confusion than we have right now.

I think the best solution is to bite the bullet, drop ngResource and rewrite the code generator to produce the same API as is on the server. See #133 for more details.

**Comment by csvan** [comment]
@bajtos - I realise I was vague in my previous comment, I did not mean to imply API breakage wrt Resource, just a utility function with the same API which nulls the third parameter if it is not provided by the user, in order to avoid this issue. I realise that this still deviates slightly from the expected API behavior, but it is preferable to passing null (which really makes no sense).

That said, I agree that your proposal is better.

**Comment by erikverheij** [comment]
I was also thinking of a wrapper. I'll stick with the workaround for the moment.

**Comment by vko-online** [comment]
I tried to define many-to-many relation with my Lead and Tag models
Lead model

    relations": {
        "tags": {
          "type": "hasAndBelongsToMany",
          "model": "Tag"
        }
      }

Tag model

    "relations": {
        "leads": {
          "type": "hasAndBelongsToMany",
          "model": "Lead"
        }
      }


First request  works

    Lead.tags.link({id: 1, fk: 1})

Second request gives error: Duplicate key for LeadTag.id

    Lead.tags.link({id: 1, fk: 1})

**Comment by abimelex** [comment]
@vko-online I guess this is intended, since the link is already set by the first request. Try to change the id or fk.
