### ISSUE TITLE
urlBase configuration

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/loopback-sdk-angular#8]
OOTB the urlBase value in lb-services.js doesn't work on iPhone b/c it's a relative url.  
You can manually edit it in the generated output file so that it works:

eg
from:

```
var urlBase = "/api";
```

to

```
var urlBase = 'http://0.0.0.0:3000/api';
```

 but it might be better if by default it picked up the baseUrl property from app.js as this would likely wrk out of the box in most cases.

**Comment by shreyas-a** [comment]
I'm still able to reproduce this bug.
Even after getting: Generating "lbServices" for the API endpoint "http://0.0.0.0:3000/api/"
the requests are going to the current port. i.e. 4000

**Comment by bajtos** [comment]
@shreyas-a thanks for chiming in. Please open a new issue and provide us with full steps how to reproduce the problem you are experiencing.
