### ISSUE TITLE
Missing parameters from API response results

### ISSUE THREAD

**Issue by albertwchang** [strongloop/loopback-sdk-angular#80]
When submitting API requests using JSON query parameters, through lb-services generated service or $http.get(), my returned results inconsistently include required nested objects.  However, when using CURL or performing a raw REST API request without $http ,the required object properties consistently return. 

See both scenarios below.  In the images below, `Green` boxes represent results WITH required nested objects; `Red` boxes represents results WITHOUT required nested objects.  All results are based on running the same query.

1) using JSON as the query
```js
var dbQuery = {
                 "filter": {
                    "where": {
                        "siteId": {
                           "inq": 27
                       }
                    },
                    "include": [
                       "eventEntries",
                       { "eventEntries": [
                             "medias",
                             "empDuty",
                             { "empDuty": ["emp","duty"] }
                          ]
                       }
                    ]
                 }
              };

//'Request' is one of the models that lb-services provisioned as a service.
Request.find(dbQuery, function(value) {
    console.log("Returned Values: ", value);
});
```
OR
```js
$http.get("http://localhost:3000/api/requests?" +JSON.stringify({
                     "filter": {
                        "where": {
                           "siteId": {
                              "inq": 27
                           }
                        },
                        "include": [
                           "eventEntries",
                           { "eventEntries": [
                                 "medias",
                                 "empDuty",
                                 { "empDuty": ["emp","duty"] }
                              ]
                           }
                        ]
                     }
                  })).then(function(results) {
                     console.log(results.data);
                  });
```
![json query1](https://cloud.githubusercontent.com/assets/3760499/4398146/78d19960-4450-11e4-8866-9048d3b6ad6e.png)
![json query2](https://cloud.githubusercontent.com/assets/3760499/4398149/7e7f474a-4450-11e4-8122-ba33a696194a.png)
![json query3](https://cloud.githubusercontent.com/assets/3760499/4398151/84113d4e-4450-11e4-90cd-2c58d27d66ef.png)

2) REST API as the query:
```js
$http.get("http://localhost:3000/api/requests?filter[where][siteId]inq=27"
             +"&filter[include][eventEntries][medias]"
             +"&filter[include][eventEntries][empDuty][emp]"
             +"&filter[include][eventEntries][empDuty][duty]").then(function(results) {
                   console.log(results.data);
              });
```
![rest api query1](https://cloud.githubusercontent.com/assets/3760499/4398185/5a08e17c-4451-11e4-842a-5bd7a8beee25.png)
![rest api query3](https://cloud.githubusercontent.com/assets/3760499/4398186/5b643512-4451-11e4-8ce3-472c442b56fc.png)
![rest api query2](https://cloud.githubusercontent.com/assets/3760499/4398191/662a20ec-4451-11e4-9ae3-b2cf098a90c4.png)

**Comment by bajtos** [comment]
I am closing this issue as it's not related to the AngularJS SDK itself.
