### ISSUE TITLE
Is User.isAuthenticated() working correctly?

### ISSUE THREAD

**Issue by gyss** [strongloop/loopback-sdk-angular#86]
Hi,
I have a test() function that prints the result of the User.isAuthenticated() function.
The first time I run the server and open the browser this function is printing "true". When I log in and log out with a example user I call test() again and prints to me "false", it works ok.
Why the first call of User.isAuthenticated() is returning "true"? I am doing something wrong?

Note: I thought It could be something about access tokens or "remember me" option from login, so I deleted all content from accessToken and User tables. And again the first call returns true.

Note 2: I workaround this issue using this comparison -> if ( LoopBackAuth.currentUserData != null ) and it works fine

**Comment by Arth95** [comment]
Hi!
I have the same issue.
First check of .isAuthenticated() is always true.
It comes false after login and logout
This is my service:

myApp.service('isLogged', ['MyUsers', function(MyUsers) {
  this.isLoggedIn = MyUsers.isAuthenticated();
        console.log('isLogged');
        console.log(MyUsers.isAuthenticated());
}]);

Can I solve it somehow?
