### ISSUE TITLE
id field always named `id` in generated resources, event for non-standard id names

### ISSUE THREAD

**Issue by pandaiolo** [strongloop/loopback-sdk-angular#89]
When configuring model with specific id field (not `id`), angular resources still expect `id` property to contain id : 

```
    "findById": {
      url: urlBase + "/Member/:id",
      method: "GET",
    },
```

My `Member` model id field is actually named `username`, which makes this confusing because sometimes `id` must be used and some other time `username` (when it's not an angular resource expected id field)

_Note : additionally, the above resources is used by calling `Member.findById({id: xxx})`, what about wrapping that in a more isomorphic `findById` that would only take the id as argument like on the server : `Member.findById(xxx)` ?_

**Comment by bajtos** [comment]
Looks like the discussion ended more than three years ago, I am closing the issue.
