### ISSUE TITLE
neq[Not equal (!=)] is not working properly

### ISSUE THREAD

**Issue by Surender246** [strongloop/loopback-sdk-angular#97]
Hi all,

I want to get the data whose "completeflag" is not equal to null.For this am using the following query.

"/api/v1/orderdetails?filter[where][completeflag][neq]=null" but i got following response

![capture](https://cloud.githubusercontent.com/assets/6521334/4843281/33dc7c48-6030-11e4-9495-2f9d1080343a.JPG)

which i noticed is that the response data is for whose "completeflag" is null, But i want only the data whose completeflag is not null, please help me to achieve this(Am using Postgresql).

Thanks in Advance.

**Comment by bajtos** [comment]
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can provide any new information to help us with resolving the issue.

**Comment by soyacz** [comment]
I'm hitting the same issue when using neq in where filter used in model scope:
```
  "scope": {
    "where": {
      "and": [{
        "publishDate": {
          "neq": null
        }
      }, {
        "archiveDate": {
          "neq": null
        }
      }]
    }
  },
```
When debuging, I see the query:
`SELECT "id", "title", "categoryId", "kindId", "shortDesc", "fullDesc", "picture", "city", "address", "postcode", "organizationId", "publishDate", "archiveDate"  FROM "Article"  WHERE ("organizationId" = 1) AND ("publishDate" IS NULL)  ORDER BY "id"`

**Comment by jac1013** [comment]
This problem is still happening today, I think with @soyacz explanation it should be possible to get a fix for it.

**Comment by bajtos** [comment]
Fair enough, I am reopening the issue.

Please check what is the `filter` argument send in the query string to the server. Does it correctly contain `neq` operators? Can you reproduce this issue without AngularJS SDK, just by running a similar "neq" query either via API Explorer or by invoking `MyModel.find` from JavaScript at server side?

I suspect this will be a bug in the server part of LoopBack, not in the AngularJS SDK.

**Comment by bajtos** [comment]
I am closing this issue as abandoned. Please open a new one if the problem still persist and you can provide answers to the questions asked in my comment above.
